### ISSUE TITLE
Don't Panic

### ISSUE THREAD

**Issue by kiliankoe** [fsr/nopanic#101]
Wie auf der FSR-Fahrt beschlossen wird die `No Panic` auf `Don't Panic` umbenannt. Ist das mit sed drüberlaufen getan oder braucht das mehr Änderungen?

**Comment by Feliix42** [comment]
DAS WURDE BESCHLOSSEN???

Da Sebastian und ich gerade einen Rewrite planen, würde ich das erstmal zurückstellen.

**Comment by sjmielke** [comment]
Mmh und dann schicken wir `sed` über die alten PDFs... so einfach wird das nicht unbedingt, da sollten wir uns nächsten Hackathon dann mal überlegen, wie wir das angehen.

**Comment by dirkonet** [comment]
Bitte richten Sie solcherlei Anfragen handschriftlich mit dreifachem Durchschlag an die Kommission zur Ablehnung der Änderung historisch gewachsener Begrifflichkeiten.

**Comment by SaschaPeukert** [comment]
Ich finde nicht, dass ihr auf eine der ältesten Traditionen, die wir als FSR haben, einfach so pfeifen solltet. Das ganze bringt nix, außer dass man als Ersti noch weniger Grund hat über die No Panic zu reden. Lasst es doch als Fnord drin.

**Comment by kiliankoe** [comment]
Issue closen ist keine Diskussionsart. Und selbst wenn das hier beschlossen wäre, sollte man sich nicht so "dagegen wehren".

**Comment by dirkonet** [comment]
Es ist einfach ein Troll-Issue, das auf einer bewussten Fehldarstellung von Tatsachen basiert. Öffne es bitte wieder, falls es jemals tatsächlich beschlossen werden sollte. Github ist kein Platz für Grundsatzdiskussionen.

**Comment by sjmielke** [comment]
**K**omplett
**E**rsti
**I**nformierende
**N**euartige
**E**inzigartige

**P**anik
**A**bweisende
**N**eu-
**I**nformatiker-
**K**ladde
