### ISSUE TITLE
"Was kann der FSR für dich tun, was kannst du für den FSR tun"

### ISSUE THREAD

**Issue by SaschaPeukert** [fsr/nopanic#103]
Es gab da doch mal so ein Plakat. Ich fände es gut, wenn dieses Plakat eine Seite in der NoPanic bekäme, dann sieht man ein paar relevante Infos besser/schneller :-)

**Comment by Feliix42** [comment]
Klingt nach einer guten Idee! Wenn wir vor dem Druck noch eine Seite frei haben, schauen wir mal, wo man das am besten unterbringen kann :)

**Comment by sjmielke** [comment]
Wenn [das hier](https://dl.dropboxusercontent.com/u/8283559/Service%20und%20Helfen.jpg) das neuste is, isses jetzt drin.

**Comment by Feliix42** [comment]
Drin und jetzt auch im "FSR-Abschnitt" angesiedelt :)
