### ISSUE TITLE
Anfrage: Information zum ehrenamtlichen Afeefa.de Projekt 

### ISSUE THREAD

**Issue by foobar0112** [fsr/nopanic#104]
Wie schon letztes Jahr, gibt es die Möglichkeit eine Seite der NO PANIC mit einer Information zu Afeefa zu füllen. Ziel: Studierende zum über das Studium hinausgehenden gesellschaftlichen Engagement animieren, bei welchen sie ihre (informatischen) Fähigkeiten einsetzen können. Ich würde mich freuen, wenn das möglich werden würde und ihr/ jemand das okay dazu gäbe. Ein Entwurf folgt.

**Comment by jgonsior** [comment]
Ja klar kann das wiede rmit rein! Bis spätestens 12.09 wäre es nett den Entwurf zu haben, gerne auch früher.

**Comment by jgonsior** [comment]
Planänderung, die No Panic wird am Montag schon gedruckt - könntest du uns das Plakat bitte so schnell wie möglich zukommen lassen? Danke!

**Comment by kiliankoe** [comment]
Aktuell ist ja das vom letzten Jahr noch enthalten, ist das outdated?

**Comment by jgonsior** [comment]
@foobar0112 schickt uns noch was aktuelles, hab ihn schon kontaktiert 😃

**Comment by foobar0112** [comment]
so ist es, kommt im laufe des Tages

**Comment by foobar0112** [comment]
PDF, A5, ohne Anschnit. Passt das so?
[NO_PANIC_NO_ANSCHNITT.pdf](https://github.com/fsr/nopanic/files/462803/NO_PANIC_NO_ANSCHNITT.pdf)
Danke! :)

**Comment by sjmielke** [comment]
Sicher, dass da nicht euer [Keming](https://cloud.githubusercontent.com/assets/1658873/18383478/0fd37c66-7686-11e6-9a3a-3415674ab4c1.jpg) gewaltig kaputt ist?

**Comment by dirkonet** [comment]
Stimme @sjmielke zu: Jedes c hat zu viel Platz hinter sich, ist die Schrift kaputt?

**Comment by kiliankoe** [comment]
Um noch meine zwei Cent dazuzugeben: pas-sendes ganz oben umzubrechen fühlt sich auch unnötig an. Ansonsten der Kerning Kram, auf jeden Fall :D

**Comment by Feliix42** [comment]
Falls noch Fixes am Plakat bis Montag kommen, einfach mal nen PR einreichen. Ich schließe das hier jetzt mal.

**Comment by foobar0112** [comment]
Hier eine schönere angepasste Version 
[NO_PANIC_NO_ANSCHNITT.pdf](https://github.com/fsr/nopanic/files/466275/NO_PANIC_NO_ANSCHNITT.pdf)

**Comment by sjmielke** [comment]
... die auch immernoch das kaputte Kerning im Text hat. Aber hey, handgefixte Überschriften sind besser als nix ;)

**Comment by foobar0112** [comment]
si, ist eben bei dem font so… :P
