### ISSUE TITLE
Angebote des Schreibzentrums

### ISSUE THREAD

**Issue by Feliix42** [fsr/nopanic#108]
Wollen wir einen kleinen Abschnitt zu Angeboten des Schreibzentrums/OFP mit rein nehmen? Und wenn ja, wo?

**Comment by cirdeirf** [comment]
Bin dafür. Wenn's sonst nirgends passt könnte man es in das Glossar packen. Andere Platzierungsmöglichkeiten wären meines Erachtens nach entweder am Ende von *Studienalltag* in der Nähe der Sprachausbildung oder in *Press F1 for help* vor oder nach dem Studienberatungsabschnitt.

**Comment by Feliix42** [comment]
Denke in der Nähe der Sprachausbildung ist es ganz gut aufgehoben. Ich werde der Frau das mal mitteilen. :)

**Comment by cirdeirf** [comment]
Hab den Text mal leicht modifiziert und eingefügt. Ich hoffe, dass es einigermaßen zufriedenstellend ist.
