### ISSUE TITLE
Main Color 2017

### ISSUE THREAD

**Issue by Feliix42** [fsr/nopanic#109]
The ESE color for this year is `#003360`. Unfortunately, this is a really dark color which doesn't set apart from the black text too well:

<img width="721" alt="normal_color" src="https://user-images.githubusercontent.com/9332912/27068267-78667504-500f-11e7-84cf-88873bb0077d.png">

I experimented a little and came up with a slightly lighter blue -  `#00437C` - which would look like this:

<img width="694" alt="new_color" src="https://user-images.githubusercontent.com/9332912/27068299-a9513ae6-500f-11e7-9e5d-e3af7591ca21.png">

<img width="698" alt="new_extended" src="https://user-images.githubusercontent.com/9332912/27068301-acb1241c-500f-11e7-9678-dd2067a509c8.png">

What do you guys think? I don't want to divert too much from the main ESE color, but we need a print-friendlier one than the originally proposed.

**Comment by 7HAL32** [comment]
`#00437C` 👍 
(Although it definitely reminds me of the old Atlassian Corporate Design from some time ago)

**Comment by cirdeirf** [comment]
Looks good! Though imo the website should have the same color (wasn't it too dark for it too?).

**Comment by tocsinDE** [comment]
+1 for `#00437C` and +1 for using it for the website as well 👍

**Comment by lucaswo** [comment]
But in the end, it doesn't even matter. 🎵
