### ISSUE TITLE
Foto des Dekans

### ISSUE THREAD

**Issue by 7HAL32** [fsr/nopanic#110]
Wir könnten auch das neue Foto von Frau Kapplusch nehmen, da ist ein bisschen grün im Hintergrund. Finde das noch besser als das jetzige.

**Comment by Feliix42** [comment]
Ich kümmere mich morgen mal darum. :)

**Comment by Feliix42** [comment]
<img width="1040" alt="screen shot 2017-06-14 at 14 22 12" src="https://user-images.githubusercontent.com/9332912/27132386-0083e962-510f-11e7-85a9-9630f942e1ae.png">

Ist der Zuschnitt so in Ordnung? Mehr Luft/weniger Luft an den Rändern? Oder Bild größer?

**Comment by Feliix42** [comment]
Hab das neue in 84c39ea eingefügt.
