### ISSUE TITLE
NoPanic 2018

### ISSUE THREAD

**Issue by Feliix42** [fsr/nopanic#115]
The Issue to rule them all!  

## Left TODO

Übrig geblieben sind folgende Punkte, die erledigt werden müssen um ein schlüssiges Gesamtwerk zu produzieren:

- [x] Wochenplan anpassen (@cirdeirf)
- [x] Das FSR-Logo auf der Rückseite ist noch bisschen unscharf, muss gefixt werden
- [x] Bilder von Uni-Gebäuden, z.B. SLUB, Alte Mensa einbauen
- [x] Spieleabendplakat an seinen richtigen Platz bewegen
- [x] Bilder Output/KIF/ESE
- [x] Layouting
- [x] Fehlerlesen (siehe Kommentare unten)
- [x] Informationen zur Wanderung (Zeitplan) korrekt?
- [x] Kapitel über die Fakultät mit Liebe überschütten (ausbauen)

## Der Plan für die NoPanic 2018:

| Seite(n) | Inhalt | Person mit Hut | ? |
| --- | --- | --- | --- |
| 1 | Cover <s>_(requires #114)_</s> | (Chrissi) | ✔ |
| 2 | Wochenplan | Pius | ✔ |
| 3 | **kurze** Checkliste (Stichpunkte) | Chrissi, Sven | ✔ |
|  |  |  |  |
| 4 | Inhaltsverzeichnis <br /> → Dotted! | Felix | ✔ |
| 5 | _"Was ist das"_ <br /> → bisschen lockerer halten, halbe Seite anstreben | Franz | ✔ |
| 6 | Grußwort <br /> → anderthalb Seiten anpeilen | Prof. Assmann <br /> (Felix) | ✔ |
| 7-10 | Checkliste **ausführlich** | Wieland | ✔ |
| 11-17 | Press F1 for Help | Sven, Wieland | ✔ |
|  | ⇒ + <s>StuGaKo</s> <br />Will man das? - Nein. | | ✔ |
| 18-21 | Anpreisung der Fak | Chrissi | ✔ |
|  | ⇒ Teich, Wiese, Sitzplätze, Öffnungszeiten,... |  | ✔ |
|  | ⇒ ascii | ascii <br /> (Felix) | ✔ |
|  | ⇒ PC-Pools |  | ✔ |
| 22-24 | Gebäude auf dem Campus | Sven | ✔ | 
|  | ⇒ SLUB (bisschen ausführlicher) |  | ✔ |
|  | ⇒ SE1/2 |  | ✔ | 
|  | ⇒ Mensen, ...|  | ✔ |
| 25-27 | Def. Module / Studienalltag (alles vorhandene) | Chrissi | ✔ |
|  | ⇒ Urlaubssemester | Felix | ✔ |
| 28-32 | Regelmäßige Veranstaltungen | Andreas | ✔|
|  | ⇒ Spieleabend <br /> Plakat bewegen? |  | ✔ | 
|  | ⇒ Stammtisch |  | ✔ | 
|  | ⇒ OUTPUT.DD |  | ✔ | 
|  | ⇒ KIF |  | ✔ | 
|  | ⇒ ESE |  | ✔ | 
|  | ⇒ CD |  | ✔ | 
| 33-41 | Modulübersicht | Tobias | ✔ |
| 42-50 | Glossar | Franz  | ✔ |
|  | ⇒ + {Kollemate, OPAL}  |  | ✔ | 
|  | ⇒ - Mensa |  | ✔ | 
| 51-53 | Links | _automatisch_ | ✔ |
|  |  |  |  |
| 54 | Kreuzworträtsel (Abkürzungen und Begriffe lernen) <br /> → Lückenfüller in general _(nach Bedarf)_ | n.N. | ✘ |
| 55 | Campusplan <s>_(requires #114)_</s> <br /> Alte Mensa einfärben | Pius | ✔ |
| 56 | Karlchen und Namen der Tutoren (und Scherzhinweise) <br /> → _"Kann Spuren von Nüssen enthalten"_ <br /> <s>_(requires #114)_</s> | Felix | ✔ |

Die Seitenzahlen sind natürlich nur grobe Ideen, aber Anfang und Ende sollten schon exakt an dieser Stelle im Heft sein.

## Bilder:

- Lucas anfragen (Alte Mensa und SLUB)

**Comment by Feliix42** [comment]
@cirdeirf and I invested some time and pain today and as of bee25a8d0469bb1b1966b742f0285f96d5e530ab we replaced PT Sans and started using Open Sans 🎉

**Comment by LeonGeorgi** [comment]
Seite 9 (E-Mail): Es gibt keine s-Nummern mehr nächstes Semester, soweit ich weiß. Vielleicht sollte man das dann ersetzen durch mamu123a@…
Wie dann allerdings die Mailadressen heißen, weiß ich nicht genau, vermutlich aber immer noch @msx.tu-dresden.de. Ich finde die Mail, in der das Stand, gerade nicht, falls ich die überhaupt je hatte.

**Comment by LeonGeorgi** [comment]
Seite 11 (studienrelevante Dokumente): Die letzten beiden Jahre gab es die PO/SO erst in den Seminargruppentreffen. Ist das dieses Mal anders?

Und ich würde die ESE-Tüte lieber überall, wo das auftaucht, ESE-Beutel nennen, ist ja jetzt kein Plastik-Scheiß mehr, sondern ein schöner Stoffbeutel.

**Comment by LeonGeorgi** [comment]
Mal abgesehen davon, dass ich Kommas vor Infinitiv mit zu schöne fände (ist aber optional), ist dieses Komma da vor dem „und“ ganz falsch: Zum Glück gibt es zahlreiche Möglichkeiten Fragen zu klären, und Hilfe zu erhalten. (Seite 13)

**Comment by kalinni** [comment]
> Seite 11 (studienrelevante Dokumente): Die letzten beiden Jahre gab es die PO/SO erst in den Seminargruppentreffen. Ist das dieses Mal anders?

Nope, wird definitiv wieder in den Treffen ausgegeben, war, meine ich, auch schon immer so, die sind ja studiengangsspezifisch. Die Frage ist aktuell nur, ob wir die im ersten, zweiten, oder - wie letztes Jahr - letzten Treffen erst ausgeben.

**Comment by Feliix42** [comment]
Wurde alles gefixed :)

**Comment by manuelthieme** [comment]
Meine Anmerkungen nach Korrekturlesen (Kleinigkeiten wie Kommafehler und letztendlich auch großigkeiten hab ich in 0c75518 bzw. #118 gefixt):
 - Die Form in der der Leser angesprochen wird ändert sich sehr oft (gerade der Teil zu den Gebäuden): "hier könnt *ihr* dies. Dort sollst *du* jenes. *Freunde der Sonne* sind besonders willkommen" -  hab versucht zumindest ein- und mehrzahl in aufeinanderfolgenden Sätzen zu vereinheitlichen.
 - Ich habe beim Lesen reflektiert und gemerkt, dass ich die Überschriften meist gar nicht mitlese. Wenn ein neues Thema also mit den Worten "In diesen Veranstaltungen" (Seite 27), also in bezug auf die Überschrift beginnt, weiß ich nicht, worum es eigentlich geht. Dann hör ich auf zu lesen, les die Überschrift und mein Lesefluss ist gestört. Ich denke nicht, dass ich der einzige bin, der es so handhabt. Vielleicht kann man darauf achten, solche Anfänge von Absätzen zu vermeiden.
 - Wusstet ihr, dass die Leerzeichen zwischen wörtern eines Satzes kleiner sind als die Leerzeichen nach einem Satzende? Das ist insbesondere bei Abk. relevant. Nach einer solchen sollte also das Leerzeichenescaped werden(-> "Abk.\ ").
 - Gibt es eine Konzept für "Anführungszeichen" oder ist das  „Willkür“?
 - sollten wir bei ascii und CD vielleicht nochmal extra auf die *neuen* ESE veranstaltungen hinweisen?
 - Wenn man seinen PDF Viewer der Wahl auf die Anzeige zweier Seiten einrichtet, werden nicht die doppelseiten des letztendlichen Heftes gemeinsam angezeigt, da die erste Seite natürlich allein außen ist. Das sollte beim letzten setzen beachtet werden.

 - Seite 3: Die Express-Checkliste ist keine Checkliste.
 - Seite 9: Email - werden die sNummern nicht abgeschafft? Oder betrifft das diesen Jahrgang noch nicht? Sollte nicht sogar der Jahrgang 2018 durch den buchstaben 'a' ersetzt werden?
 - Seite 10: Eduroam zugang ist dann bei änderung des Zugangs auch entsprechend anders
 - Seite 11: gedruckte Studiendokumente gibt es, wenn überhaupt, in den Seminargruppen, nicht in der ESE-Tüte
 - Seite 11: Da scheint ja unten noch Platz zu sein. Vielleicht kann man Wahlhelfer erwähnen.
 - Seite 14: 3. Absatz - "Er ist Mitorganisator..." klingt als bezüge sich das "Er" auf den davor erwähnten Spieleabend. Wusste jetzt nicht direkt, wie ich das ändern soll.
 - Seite 29: Die Diplomer sind nicht verpflichtet Englisch zu lernen. Es sind auch andere bewertete Sprachkurse möglich. Wenn man anderweitig Scheine einbringt, reicht sogar ein einzelner Sprachkurs.
 - Seite 38: den Roboterwettbewerb gibt es doch garnicht mehr, oder?
 - Seite 55: Der Blocksatz der Überschrift ist komisch, wenn es zu mehr als einer Zeile kommt (Überfachliche        Qualifikationen)
