### ISSUE TITLE
Switch to Exo 2

### ISSUE THREAD

**Issue by tobias-haenel** [fsr/nopanic#116]
There is an updated version of Exo - https://www.fontsquirrel.com/fonts/exo-2

We should probalby switch to it. E.g. 'W' looks much nicer.

**Comment by sjmielke** [comment]
I chose Exo over Exo 2 back in the day because I think the latter somehow... lacks some of the character that the former has. 🤷
The improvements (or the "smoothing", really) were made primarily to make Exo 2 work well for running text iirc, which doesn't really concern us.

**Comment by tobias-haenel** [comment]
The 'W' issue originiated from a bug, that was fixed through an update of Exo 1. Therefore it should be sufficient to reinstall Exo before creating the final PDF. The fixed version should have a symmetric 'W'.

**Comment by Feliix42** [comment]
Another issue always was that the FSR Corporate Design use{s, d} Exo as font, because our printer is unable to print Exo 2. Hence, we used Exo 1 here as well to be consistent :D

**Comment by tobias-haenel** [comment]
Ok, then we should stick to updating the Exo 1 version, that is installed on the build system.
