### ISSUE TITLE
English Version (for real this time!)

### ISSUE THREAD

**Issue by Feliix42** [fsr/nopanic#117]
Okay, since it seems that we will indeed be able to write an english version this year, this issue will act as tracking issue.

For the realisation, I would recommend opening a separate branch. [`mdBook`](https://github.com/rust-lang-nursery/mdBook) seems like a good option for writing the version, as it looks good on browser and mobile and the printed version is neat, too ([here](https://doc.rust-lang.org/book/second-edition/index.html) an example).

Roadmap:

- [ ] Define, what contents should be cloned into the english version

**Comment by jkrbs** [comment]
I would rather create a new repository for the english version, because it will be a completely different project. no print, no yearly version, not in latex. we would have to open an orphan branch. So let's open a new repo and start tracking content issues there.

**Comment by Lodifice** [comment]
> not in latex

I think there is a mistake in your statement, but maybe I'm wrong and you guys are finally moving to groff.

**Comment by Feliix42** [comment]
Why no LaTeX? :eyes:
I'd like to suggest a `latex -> pandoc -> html` workflow. Or [this](https://github.com/latex2html/latex2html/) instead. 

But I also see a point for using a static site generator like hugo. In that case, I could settle for `latex -> pandoc -> markdown -> hugo -> html`.

**Comment by kiliankoe** [comment]
needs more quine

**Comment by Feliix42** [comment]
See [fsr/master-manual](https://github.com/fsr/master-manual). 🎉
