### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by jkrbs** [fsr/nopanic#120]
There should be a FAQ Page, because people don't read the entire book and ask their  questions in person, instead of looking them up.

**Comment by Feliix42** [comment]
Where should we put it? I would advocate for a place relatively early in the book (i.e., before or after the deans preamble).

**Comment by jkrbs** [comment]
imho directly after the dean's preamble would be the best place. we also should start collecting questions

**Comment by Feliix42** [comment]
@Feliix42 macht einen verweis mit `\menukeys` für die Seiten. Farbe: orange

**Comment by Feliix42** [comment]
> *Was machen diese Bobbels da im Foyer?*

**Comment by RobertPeine** [comment]
Vielleicht findet man auch hier noch die ein oder andere Frage, die man aufnehmen könnte: https://tu-dresden.de/ing/informatik/studium/faq
