### ISSUE TITLE
Inhaltsverzeichnis

### ISSUE THREAD

**Issue by jkrbs** [fsr/nopanic#122]
schicker machen und mit "must read" und "read later" tags versehen

**Comment by Feliix42** [comment]
Die Optik ist schon mal repariert, ich habe den Fettdruck rausgenommen (meine Augen tun endlich nicht mehr weh \o/) und die Font auf Open Sans geändert.

**Comment by jkrbs** [comment]
was ist hier noch zu tun? oder kann das issue weg?
