### ISSUE TITLE
Spacing über Überschriften

### ISSUE THREAD

**Issue by jkrbs** [fsr/nopanic#125]
Es gab die Diskussion beim Treffen, ob das Spacing erhöht werden soll, damit das Heft nicht so voll aussieht. Ich halte das für eine sinnvolle Idee. Also einfach einen `\vspace` drüber?

**Comment by Feliix42** [comment]
*Oder*, man entfernt diesen Befehl hier:

https://github.com/fsr/nopanic/blob/30374f91a5c573d049652b35af91abec485507f8/preamble.tex#L1

der den natürlich auftretenden Space getötet hat. 🙃
Getan in 8657c4db5c513e3725553d1309a5bc06817d0a54. Ist das so genehm vom Space her? Finde es ganz ok (man kann es beim setzen ja ggf immer noch reduzieren, wenn es beim Setzen Probleme macht.
