### ISSUE TITLE
Anpassung regelmäßige Veranstaltungen

### ISSUE THREAD

**Issue by jkrbs** [fsr/nopanic#126]
+ Schreibcafé
+ Dies Academicus
- KIF

**Comment by Feliix42** [comment]
KIF wurde entfernt, Das CD wurde forcefully moved ✔️

**Comment by jkrbs** [comment]
ich schreibe mal einen Text zum Schreibcafe und zum Diesacademicus

**Comment by jkrbs** [comment]
Dies Text sollte noch überarbeitet werden, ich finde es relativ schwierig, zu beschreiben, was am dies passiert. 🧀 5b20876

**Comment by ChrissisCorner** [comment]
Wenn wir den Dies Academicus drinne haben, wollen wir dann auch die Lange Nacht der Wissenschaft ergänzen?
