### ISSUE TITLE
Glossar be gone!

### ISSUE THREAD

**Issue by Feliix42** [fsr/nopanic#127]
Das Glossar ist viel zu umfangreich und wird eher wenig bis gar nicht von den Lesern beachtet. Da es jetzt ohnehin durch das FAQ (#120) abgelöst wird, kann das Kapitel stark gekürzt bzw. gestrichen werden. Allerdings sollte Sorge dafür getragen werden, dass die relevanten Inhalte sich andernorts noch irgendwo im Heft wieder finden, damit nichts verloren geht.

**Comment by jkrbs** [comment]
Ich würde das Kapitel komplett streichen. Die Inhalte sind im Heft vorhanden, bzw. werden in der Faq stehen. 👋

**Comment by Feliix42** [comment]
Ich habe jetzt alles bis auf ~1 Seite gestrichen und oder in anderen Kapiteln ergänzt. Was jetzt noch im Glossar steht muss entweder bisschen aufwendiger verschoben werden (SSH zb?) oder man muss sich überlegen, ob man es behalten will und wo es hin soll (Kinos, AG DSN).

**Comment by jkrbs** [comment]
ich würde ssh raus kicken, weil es für fast niemanden relevant ist. Niemand wird deswegen anfangen ssh zu den login Servern zu nutzen

**Comment by Feliix42** [comment]
- AG DSN -> Vermerk in der FAQ und auf deren Leistungen bei "Wohnung"
- <s>Bücher</s>
- <s>Kino</s>
- <s>Krankenversicherung</s>
- Rundfunkbeitrag -- als Satz bei "Wohnsitz anmelden" in der Erstsemestercheckliste aufnehmen?
- Semesterticket -> schieben in "FAQ" mit Link auf die StuRa-Seite dazu
- <s>xkcd</s> 😭
