### ISSUE TITLE
Cover Vorschlag

### ISSUE THREAD

**Issue by phanpatrik** [fsr/nopanic#134]
[the_manual_cover.pdf](https://github.com/fsr/nopanic/files/3614035/the_manual_cover.pdf)

hab' mich auch mal dran versucht.

**Comment by phanpatrik** [comment]
@EddyLoose, @Feliix42

**Comment by RobertPeine** [comment]
An sich nicht schlecht, aber mir wird nicht so ganz klar, was Schraubenschlüssel, Pappeschnipsel und F1 gemeinsam haben.

**Comment by phanpatrik** [comment]
Manual = Schraubschlüssel (irgendwas zusammenbauen, etwas nach Anleitung bauen)

F1 = Hilfe

Pappschnipsel = Do it yourself Motto

**Comment by RobertPeine** [comment]
Ich bin da kein Fan von, aber klar braucht man irgendetwas, um das Cover zu füllen. Ich hätte halt irgendein Bild in den Hintergrund gelegt oder so.

![irgendwieso](https://user-images.githubusercontent.com/17642627/64925687-d3634080-d7f4-11e9-840c-00cf02f877bd.jpg)

**Comment by phanpatrik** [comment]
Ich kann auch ein mix up machen. Danke für dein Feedback 😘

**Comment by RobertPeine** [comment]
Ist nur meine persönliche Meinung. Ich habe vernommen, dass dein Vorschlag @Feliix42 sehr gefällt.

Aus meiner Sicht, dürfte "The Manual" gern noch etwas größer sein, wenn es denn zum Rest passt.

**Comment by phanpatrik** [comment]
Ich habe nochmal auch aus meinem Umkreis ein wenig Feedback aufgenommen und passe minimal an

**Comment by phanpatrik** [comment]
[the_manual_cover.pdf](https://github.com/fsr/nopanic/files/3617701/the_manual_cover.pdf)

Angepasst und demokratisch dazu entschieden. :)

**Comment by kiliankoe** [comment]
Aber das ist clearly ne Apple Bluetooth Tastatur und auf macOS öffnet F1 nicht die Hilfe 🙈😅

**Comment by phanpatrik** [comment]
Und wenn ich da einfach ein Microsoft Logo draufpacke!!??1elf @kiliankoe
