### ISSUE TITLE
Dank an

### ISSUE THREAD

**Issue by niklaskeerl** [fsr/nopanic#136]
Auf der letzten Seite beim Dank an stehen die ESE Helfer von der ESE vom letzten Jahr.

**Comment by Feliix42** [comment]
Was hatte ich über den Zustand der Rückseite gesagt? :D

**Comment by RobertPeine** [comment]
Nicht so sarkastisch sein ... Immerhin wird ein Issue jetzt daran erinnern, dass die Namen ausgetauscht werden müssen.

**Comment by Feliix42** [comment]
Das war kein Sarkasmus :open_mouth:
Ja, das stimmt :)

**Comment by niklaskeerl** [comment]
Es tut mir leid, hab die Mail nicht ganz gelesen.
