### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by PeterNerlich** [fsr/nopanic#144]
Viele Grüße aus Görlitz!
Vor meinem Studium hier war ich ein Jahr an der TUD und konnte eure großartige ESE und das zugehörige Heft miterleben. Jetzt ist auch der FSR I der HSZG soweit, genau soetwas zu versuchen.

Wir würden gerne eure großartige Vorarbeit als Basis nutzen, aber dafür wäre es schön, wenn ihr eine Lizenz hinzufügen würdet.

**Comment by Feliix42** [comment]
Oha, ich hätte schwören können, dass wir die Unterhaltung schon irgendwann mal hatten. Scheint aber nichts bei rausgekommen zu sein. :sweat_smile:

Freut mich, dass ihr das Heft auch benutzen wollt! Wir teilen unsere Arbeit gern.

Also für das [KIF-Heft](https://github.com/fsr/kif470-heft) haben wir damals als Lizenz [`CC BY-NC-SA 4.0`](https://creativecommons.org/licenses/by-nc-sa/4.0/) gewählt. Ich bin mir nicht sicher, ob das die Richtige hierfür ist, aber streng genommen ist das Heft ja keine Software, also passen Apache/MIT/GPL/MPL/BSD nicht.

**Comment by PeterNerlich** [comment]
Ping! :tada: 

Meanwhile haben wir hier angefangen, unseren Fork auseinanderzunehmen: https://gitlab.hrz.tu-chemnitz.de/fsr-i/the-manual

**Comment by jkrbs** [comment]
Ich habe das mal erledigt. Im Team waren sich alle einig, es hat nur niemand gemacht ;)
