### ISSUE TITLE
Ausrichtung der No Panic!

### ISSUE THREAD

**Issue by dirkonet** [fsr/nopanic#19]
Soll die diesjährige No Panic! ein "No Bullshit Guide to the ESE and the First Semester" sein oder ein Nachschlagewerk?

Pro Nachschlagewerk: In einer freien Minute oder mal über's Wochenende kann man als Erstie dann mal ein paar zusätzliche Informationen nachschlagen, zum Beispiel die Geschichte der Gebäude/hinter den Gebäudenamen. Außerdem wird die No Panic! bei Veranstaltungen wie Uni Live ausgelegt, sodass sich dann Studieninteressierte schon einmal informieren könnten. Die No Panic! sollte also mehr Informationen enthalten, als die Tutorien den Ersties mitgeben.

**Comment by kiliankoe** [comment]
Wird wohl auch kaum was für 2015, oder? :D

**Comment by Feliix42** [comment]
Ist das hier eigentlich Kunst oder kann das weg? :D

**Comment by sjmielke** [comment]
Ist ein Thema, was man halt schon nochmal irgendwie im Hinterkopf halten kann, deshalb v2017 ;)

**Comment by Feliix42** [comment]
Zusammen mit #47, #96 und natürlich ganz besonders #101!

**Comment by kiliankoe** [comment]
Ey, das ist alles historisch wertvoll und total relevant für irgendwann™
