### ISSUE TITLE
Formatierung und Kleinigkeiten

### ISSUE THREAD

**Issue by dirkonet** [fsr/nopanic#45]
Bitte bei der nächsten Version noch einmal ordentlich nach Hurenkindern, Schusterjungen und sonstigen Formatierungsproblemchen suchen. Beispiele in der v2014:

* Vorwort des Dekans: Zwei Schusterjungen, Verschiebung des ersten auf Seite 7 würde alles verschönern.
* Worttrennungen über Umblättern hinweg, zum Beispiel "Es-sen" im Glossar, E-Meal, Seite 37
* Worttrennungen in Emailadressen und Eigennamen, zum Beispiel spi-ritus rector (Seite 23), auditori-um@ vs mail.zih.tu-dresden.de (Seite 25 bzw. 34)
* Glossar-Schusterjungen/Hurenkinder: Bibliothek, Integrale, Rekursion, SHKs
* Zeilenumbrüche in Links, die noch hätten gekürzt werden können: 21, 23
* Links im inf-CMS (6, 7, 8) gehen auch ohne &ln=de

**Comment by sjmielke** [comment]
Ggf. auch folgende Anmerkung von @frankhedecke umsetzen:

> Der Ascii und der Count-Down Artikel sollten vertauscht werden.
> Dann wäre der Ascii Artikel neben dem Spieleabendplakat und das CD hätte eine Doppelseite, ohne umblättern.

**Comment by jgonsior** [comment]
Ich habe mal den Ascii und den Count Down Text vertauscht.

**Comment by sjmielke** [comment]
Sollte für dieses Jahr alles toll sein, entsprechend schiebe ich den Milestone mal eins weiter^^ (oder wir schließen das Issue einfach und machen nächstes Jahr ein neues sauberes auf)

**Comment by dirkonet** [comment]
# Formatierung und Kleinigkeiten, Ausgabe 2016

## Zeitplan
* Seminargruppentreffen wenn möglich als Seminargruppen-treffen umbrechen
* Campusschnitzeljagd als Campus-Schnitzeljagd oder Campus-schnitzeljagd umbrechen

## Express-Checkliste
* ZIH-Passwort ändern -> ZIH-Login aktivieren
* ZIH-Dienste einrichten? Was soll ich tun?

## Erstsemester-Checkliste
* Erstpasswort ändern -> ZIH-Login aktivieren, "musst du dein ZIH-Login mit dem IDM-Coupon aktivieren. Den Coupon solltest du an deine im Bewerberportal angegebene Emailadresse zugestellt bekommen haben."
* Mail Account -> E-Mail
* "Du bekommst vom ZIH ein Exchange-Postfach \textit{s1234567@msx.tu-dresden.de} und einen Alias"…
* WLAN: sowohl _als_ auch. Login -> ZIH-Login; sNummer als sXXXXXXX, sNummer wie im Glossar oder s1234567 wie unter Email?

## Vorwort
* im Satz zum ascii Doppelpunkt durch Komma ersetzen, ascii klein schreiben (und in monospace setzen wie auf Seite 21?)

## Glossar
* Fakultät wird erklärt -> auch Bereich erklären?

## Sonstige Inhaltsseiten
* Seite 10: Andreas-Pfitzmann-Bau.
* Seite 14: Email-Adressen und Namen möglichst nicht umbrechen
* Seite 16: Xelatex tut komische Dinge mit Wörtern wie Seminargruppenmentor beim Umbruch
Seite 27: Link 35 von inf.tu… auf www.inf.tu… ändern, Zertifikat ohne www existiert nicht
Seite 28: "da der Lehrplan für die Professoren mehr oder minder vorgeschrieben ist" von wem?
Seite 30: Sprachausbildung: Die Links zu sprachausbildung.tu-dresden.de und Login tauschen, den zur Sprachschule streichen
S. 51: Kartenhighlights noch auf ESE-Farbe umstellen

**Comment by Feliix42** [comment]
Ich nehme an, das man für die Coupons auf https://idm-coupon.tu-dresden.de verweisen kann?

**Comment by dirkonet** [comment]
Kann man, steht aber auch mit in der Coupon-Email.

**Comment by Feliix42** [comment]
Gut, danke. Lieber bisschen redundant :)
