### ISSUE TITLE
Schnittkanten

### ISSUE THREAD

**Issue by kiliankoe** [fsr/nopanic#46]
Nachdem Saxoprint die Reklamationsanfrage wegen der kleinen weißen Kanten (auf die sie uns vielleicht oder auch nicht selbst hingewiesen haben) zurückgewiesen hat, wäre es vielleicht praktisch, zur nächsten Version mit darauf zu achten 2mm Schnittkanten mit dabei zu haben. Werde einen Hut essen, wenn LaTeX hierfür keine Option hat.

> Sie haben Ihr Format auf 148 x 210 mm angelegt. Richtig wäre jedoch 152 x 214  mm inkl. 2 mm Randanschnitt gewesen.

Beim "Profi-Datencheck" hätten wir dann wohl einen Hinweis dazu bekommen, aber ich kann nicht sagen, dass mich die Kanten jetzt großartig stören.
Netterweise haben Sie uns einen Gutschein für einen kostenlosen Profi-Datencheck mitgegeben `MDP15ECHECK`. Ist aber nur die nächsten beiden Monate gültig, darf sich hier also klauen wer will :D

**Comment by sjmielke** [comment]
sebastian zu lucas: weißt du noch, warum wir bei der nopanic die schnittkanten wieder rausgenommen haben? o.O
lucas zu sebastian: weil der fehler nicht die schnittkanten waren, sondern dass das frontbild nicht genau A5 war
