### ISSUE TITLE
Werbung Ausleihsystem

### ISSUE THREAD

**Issue by frankhedecke** [fsr/nopanic#48]
Die NoPanic sollte eine Seite haben in der die Ausleihmöglichkeiten beworben werden. Ich meine den quix Kram.

**Comment by kiliankoe** [comment]
Hätte da jemand Lust einen kleinen Text für zu schreiben? Sicherlich wäre ein 3-Zeiler auf der FSR Seite völlig ausreichend. 

Links zu [Leihgegenständen](https://www.ifsr.de/_media/leihmaterial_1_.pdf) und [Leihordnung](https://www.ifsr.de/_media/leihordnung.pdf) sind eigentlich das Wichtigste daran.

**Comment by kiliankoe** [comment]
Anscheinend besteht schon ein verschollener Text von @hannibal42 :smiley:

**Comment by sjmielke** [comment]
Das ist besagter Text von Simon:

Der FSR bietet für alle Studenten der TU Dresden verschiedene Geräte und Materialien zum ausleihen an. Ausgeliehen werden können unter anderem verschiedene Raspberry Pis, eine Oculus Rift und Lego Mindstorms. Eine Liste mit allen Ausleihgegenständen findet ihr auf unserer Website. Wenn ihr etwas ausleihen wollt, dann bringt bitte beim ersten mal euren Personalausweis mit, damit wir auch einen Leihschein ausstellen können.

Könnte so in den FSR-Text integriert werden.
