### ISSUE TITLE
Roboto-font zu Requirements hinzufügen

### ISSUE THREAD

**Issue by Feliix42** [fsr/nopanic#49]
Zumindest mit MiKTeX unter Windows kriege ich ohne das Nachinstallieren von der Roboto-Font von XeLaTeX einen Fehler geworfen, "Font not found".

Angenommen, es war nicht meiner Unfähigkeit geschuldet, sollte es mit in die Requirements, meine ich. :D

**Comment by sjmielke** [comment]
Jop, die Seitenzahlen sind in Roboto, siehe https://github.com/fsr/nopanic/blob/master/nopanic.tex#L50
Könnte man eigentlich auch... lassen. Oder man packts in die README rein, haste schon recht. 

Müsste man mal gucken, ob ich mir damals was dabei gedacht hatte, die Seitenzahlen nicht auch in PT Sans oder Exo zu haben... Wahrscheinlich nicht, ein dritter Font für Seitenzahlen klingt nicht so :D
