### ISSUE TITLE
Zusätzlicher Content für ausländische Studenten

### ISSUE THREAD

**Issue by Feliix42** [fsr/nopanic#52]
Wie wir besprochen hatten, wäre es praktisch, wenn sich mal einer mit dem Verantwortlichen für ausländische Erstis oder Master-Studenten unterhält und einen zusätzlichen Artikel für die englische NoPanic schreibt, damit die Leute dann auch eine Anlaufstelle haben, an die sie sich wenden können.

Ggf. kann man sich auch noch mal mit einem Koordinator vom ERASMUS-Programm absprechen und fragen, ob die noch Anregungen haben.

**Comment by jgonsior** [comment]
Im August kann ich mal die Erasmus Koordinatorin der Informatik Fakultät diesbezüglich anschreiben, oder gibt es da bereits Informationen zwischen ihr und dem FSR welche an mir vorbeigegangen sind? Ich will ja nicht, dass sie am Ende doppelt gefragt wird :-)

**Comment by kiliankoe** [comment]
@kalinni meinte eben, dass das unnötig sei. Ich refernzier' das jetzt einfach erstmal so.

**Comment by jgonsior** [comment]
Na dann halt nicht. Die ausländischen Studenten werden sicherlich auch irgendwie anders über Sachen informiert die nur für sie wichtig sind.

**Comment by dirkonet** [comment]
Für die internationalen Studierenden in den deutschsprachigen Studiengängen gibt es [das Tutorenprogramm des AAA](https://tu-dresden.de/internationales/int_stud/tutorenprogramm/index_html) mit seinen Infoveranstaltungen, auf die die internationalen Ersties hingewiesen werden.

**Comment by kalinni** [comment]
Um genau zu sein, war Kilians Aussage sehr, sehr kurz gefasst. Was ich eigentlich gesagt hatte, war, dass ich (auch bezüglich der ESE) Kontakt mit den Tutoren für die ausländischen Studierenden habe und wir dort unsere Infos her bekommen können. Das ist dann auch eine direktere Quelle als die Erasmus-Koordinatorin.
Den Kontakt hat auch Sönke und der ist insgesamt für den Kram zuständig.

**Comment by jgonsior** [comment]
D.h. eigentlich wollte Kilian schreiben, dass man den Sönke fragen muss, was alles in die NoPanic für die englischen Studenten mit rein muss?

**Comment by kalinni** [comment]
An sich weiß er Bescheid, er ist halt zuständiger für den Bereich und als solcher auch im Wiki eingetragen. Insbesondere hat er auch den Auftrag, dem Website-Team Infos für die englische Seite zukommen zu lassen.
Aber nachfragen ist trotzdem immer ne gute Idee. ;)
