### ISSUE TITLE
Links der englischen NoPanic-Version

### ISSUE THREAD

**Issue by Feliix42** [fsr/nopanic#54]
Die Links müssen für die englische Version angepasst werden:
- soweit möglich, sollten zu allen Links aus der Linkliste die englischen Pendants verwendet werden, um ein einheitliches "Gesamtpaket" abzuliefern
- **[Idee]** evtl. kann man mit dem iFSR abklären, ob man diese Shortlinks, die in der deutschen Version sind, auch für die englische Version arrangieren kann

**Comment by sjmielke** [comment]
Das super powered-by-PHP-oneliners-and-an-extremely-lazy-admin-Linksystem? Kriegen wir hin :D
Für den TeX-Teil obliegt es dann halt der Disziplin der Übersetzer, dafür zu sorgen, dass die Links da 1:1-Pendants haben, das technisch zu machen würde den aktuellen "Workflow" kaputtmachen und die Magie ruinieren :)
