### ISSUE TITLE
Auditorium-Text übersetzen

### ISSUE THREAD

**Issue by Feliix42** [fsr/nopanic#55]
Der Text über das **Auditorium** muss auf Englisch übersetzt werden.

**Comment by kiliankoe** [comment]
Wie tot ist das Auditorium mittlerweile eigentlich? Klar, cooles Projekt, für RN noch sehr nutzbar, aber sonst? Will's nicht unbedingt kicken, nur mal darüber nachdenken :P

**Comment by JustusAdam** [comment]
Wir haben damals für's SWT Projekt ziemlich viel benutzt.

**Comment by kiliankoe** [comment]
> damals

Ja. Gab auch mal ne Zeit als das Hick'n'hack für so ziemlich alles recht aktiv genutzt wurde.

**Comment by JustusAdam** [comment]
Damals als in "vor nem halben Jahr"

**Comment by kiliankoe** [comment]
Oh. Na gut :D
