### ISSUE TITLE
Grußwort des Dekans -> Englisch

### ISSUE THREAD

**Issue by Feliix42** [fsr/nopanic#62]
Das muss natürlich seinen Weg auch irgendwie in die englische Sprache finden. 

Gibt es eigentlich ein Neues für dieses Jahr? :smile: 
Weiß nicht, ob man Prof. Baader irgendwie dazu bewegen kann, uns das gleich zweisprachig zu geben, wenn er ein neues schreibt.

**Comment by kiliankoe** [comment]
> Gibt es eigentlich ein Neues für dieses Jahr? :smile: 

Ich würd's kaum vermuten, aber nachfragen sollten wir auf jeden Fall. Dann klärt sich auch gleich das mit der englischen Variante ;)
