### ISSUE TITLE
Studienablauf übersetzen

### ISSUE THREAD

**Issue by Feliix42** [fsr/nopanic#64]
Der Text über den **Studienablauf** braucht auch ein englisches Remake. Freiwillige vor! :wink:

**Comment by dirkonet** [comment]
Nicht übersetzen, anpassen. Die nicht-deutschsprachigen englischsprachigen Studierenden studieren ja CL oder DSE, gegebenenfalls CSE.

**Comment by Feliix42** [comment]
Also meinst du, man sollte das in der englischen Ausgabe gleich ganz streichen?

**Comment by dirkonet** [comment]
Oder halt entsprechend an die relevanten Studiengänge anpassen, damit die englischsprachige Ausgabe sinnvoll bleibt. Gibt es eigentlich irgendwo eine Beschreibung der Zielgruppe und Auflage der englischen NeinPanik?

**Comment by Feliix42** [comment]
Zielgrppe an sich wurde bisher nicht spezifisch definiert. Gedacht für Studenten, die von außerhalb hierher kommen und ihren Weg zur ESE-Woche gefunden haben. Die Auflage wird folglich nicht allzu hoch, meine ich. Oder?

NeinPanik klingt aber nett :D

**Comment by dirkonet** [comment]
Es gibt halt mehrere Gruppen von internationalen Studierenden:

1. CL, DSE: meist englischsprachig neben der Muttersprache, oft deutsch nur als Drittsprache oder gar nicht, ca. 50 Leute
2. Austauschprogramme in den deutschsprachigen Studiengängen (Erasmus, Agricola,…): 1-2 Semester hier, sprechen zum Teil nur Deutsch neben der Muttersprache, englisch nur als Drittsprache oder gar nicht, ca. 5-15 Leute
3. Austauschprogramme in den englischsprachigen Studiengängen: ähnlich 1., aber nur 1-2 Semester hier, ca. 5-10 Leute
4. internationale Erstsemestler in den deutschsprachigen Studiengängen: deutschsprachig, ca. 30 Leute

2 und 3 sind oft in höheren Semestern

2, 3 und 4 sind Zielgruppen des [AAA-Tutorenprogramms](http://tu-dresden.de/internationales/int_stud/tutorenprogramm/index_html) und bekommen viele ihrer Informationen dort (ich war da mal Tutor, aktueller Tutor jeweils erreichbar unter tutor-inf@tu…)

4 sind Zielgruppe für die Seminargruppen

Eine rein englischsprachige NeinPanik hätte als Zielgruppe eigentlich nur 1 und 3, insgesamt ca. 50 Leute. Dort sollte sich auf jeden Fall mit den entsprechenden Programmkoordinatoren abgesprochen werden, da die teilweise auch eigene Infoveranstaltungen bieten.

Zu NeinPanik siehe #53 ;)
