### ISSUE TITLE
Werbung in der NoPanic

### ISSUE THREAD

**Issue by Feliix42** [fsr/nopanic#66]
Wollen wir die Werbung auch in Englisch machen? Oder sagen wir einfach "Werbung ist Werbung, bei der Auflage der englischen Version lohnt das nicht"? Ich finde letzteres fast besser.

**Comment by kiliankoe** [comment]
> Werbung ist Werbung, bei der Auflage der englischen Version lohnt das nicht

:+1: 

Alles andere sprengt den Rahmen eher.
