### ISSUE TITLE
Assoziierte mit erwähnen

### ISSUE THREAD

**Issue by kiliankoe** [fsr/nopanic#70]
![](http://i.giphy.com/xT1ksK7W5KS3e.gif)

**Comment by Feliix42** [comment]
Meint Assoziierte hier contributor oder andere Menschen? :smile:

**Comment by kiliankoe** [comment]
In erster Linie die assoziierten Mitglieder des FSR, bin jedoch auch dafür die Menschen, die hier beitragen, mit hervorzuheben.

**Comment by sjmielke** [comment]
Zertifizierte FSR-Assoziierte™ zu den FSR-Seiten, NoPanic-contributors könnte man aber drüber reden, ob man die wirklich wieder hinten drauf machen will (gab da ja mal hinten ne Zeile mit Namen, bin nicht mehr sicher, warum wir die rausgenommen haben, Platzgründe oder so).

**Comment by kiliankoe** [comment]
> bin nicht mehr sicher, warum wir die rausgenommen haben

Im Zweifelsfall aus formattechnischen Gründen :D

**Comment by dirkonet** [comment]
ESE-Helfer: Sollten vielleicht wieder rein. Assoziierte: Find ich nicht sinnvoll.

**Comment by kiliankoe** [comment]
Klingt nach ner sinnvollen Idee.

**Comment by lucaswo** [comment]
Hat sich das mit c076266c41b7718c8db74740150da60397c0adfc geklärt?

**Comment by kiliankoe** [comment]
Eigentlich war der ursprüngliche Gedanke ja für ne weitere Section an der FSR Seite mit "Gesichter, die du wahrscheinlich auch oft sehen wirst". Aber das ist sicher auch hinfällig :P

**Comment by lucaswo** [comment]
Dirk:
> ESE-Helfer: Sollten vielleicht wieder rein. Assoziierte: Find ich nicht sinnvoll.

Kilian:
> Klingt nach ner sinnvollen Idee.

Hiermit ekläre ich die Assoziiertendebatte für beendet.

**Comment by kiliankoe** [comment]
![](http://i.giphy.com/MUVFUXkCp0DNS.gif)
