### ISSUE TITLE
Ja, Panik!

### ISSUE THREAD

**Issue by sjmielke** [fsr/nopanic#71]
Da plötzlich und völlig unverhofft Ende August ist, müssen wir mal langsam alles zusammenkriegen.
Da wäre die erste Frage: wie stehts um die englische NoPanic? Gibts da schon Texte und scheitert es bloß an der Einbindung in Struktur?
Weil wenn nicht brauchen wir damit jetzt auch nicht mehr anfangen würde ich sagen.

Ich hab des weiteren heute mal durch das alte PDF gelesen und ein paar Dinge rausgeschrieben, die geändert werden müssen (nein, ich mache nicht für jeden Punkt ein Issue auf, schlimm genug, dass man die zig aufgespaltenen englischen Issues erstmal wegfiltern muss, finde ich persönlich):

---

**Aktuellere Liste weiter unten!** Irgendwie alles doch nicht ganz so sauber. Wär der gitter chat doch besser gewesen? Wer weiß.

---

Global:
- ~~bleibt grün die Hauptfarbe oder wird es... lila? :S~~
- ~~s/INF/APB/g~~
- ~~neuer Ablaufplan~~
- ~~neue Helferliste~~
- ~~neuer Campusplan~~
- neue Werbung
- ~~Vorder- und Rückseite doch nochmal de-schnittkant-ifizieren?~~
- ~~Alle Links prüfen!~~
- ~~https wo möglich~~
- ~~Alles in allen Richtungen korrekturlesen!~~
- Alle offenen Issues: https://github.com/fsr/nopanic/issues?q=is%3Aopen+is%3Aissue+-label%3A%22english+version%22+milestone%3Av2015
  * ~~Ausleihsystem? (simon ist angeschrieben worden)~~
  * ~~Schiffe versenken (wenn wer lust hat, da was zu bauen, super)~~ v2016
  * ~~Assoziierte erwähnen (alles bleibt, wies ist? fsr-assoziierte wird halt etwas schwer zu umfassen, mitwirkung an der nopanic ist eher sinnlos, wenn man nicht alle der letzten jahre aufzählt, denn die haben ja eh um größenordnungen mehr content beigesteuert als der aktuelle jahrgang das tun wird)~~
  * ~~Schnittkanten (sind zwar dank lucas drin, bringen aber nix, wenn wir die bilder nicht entsprechend strecken! bin ich gerade dran)~~
  * Formatierung... kommt später würde ich sagen.

Vorwort:
- ~~Prof. Baader wird angeschrieben, sobald ich wieder SMTP kann. Mal schauen, was passiert.~~

Studienbetrieb:
- ~~Prüfungen austragen: 3 Werktage? Wirklich? Für alle?~~
- Scheine wirklich erwähnen? Hab ich nie was mit zu tun gehabt.
- ~~Master Inf braucht wieviel Englisch? Hab mal 4 SWS reingeschrieben, wie Diplom, bitte richtigstellen.~~

Erstsemester-Checkliste:
- ~~USZ mal auf die Sache mit der Sporthalle hinweisen, keine Ahnung, wie viel Einfluss das hat.~~
- ~~Programmierkurse: was/wann?~~
- ~~Prüfungseinschreibung: Nikolausklausur erwähnen!~~
- Rückmeldung: so spezifisch?

Modulübersicht:
- ~~Forschungslinie auch Nicht-Diplomern empfehlen?~~
- ~~Allg. Basisqualifikationen: ist mir neu, dass das eine fixe Veranstaltung ist, ich dachte da kann man sich auch Dinge wählen?~~

F1:
- ~~Studienberater aktuell?~~

auditorium:
- Ja/~~Nein?~~

FSR:
- ~~neues Logo, neue Gesichter (wollen wir das Benutzen der Wahlbilder erzwingen?)~~
- ~~das blöde Grillbild durch ein Bild von Kilian mit Pinguin ersetzen~~

ZIH:
- msx-Adresse erwähnen
- SLM erwähnen (erstpasswortänderung und so vielleicht dazu reinbringen?
- julius todo

Glossar:
- ~~Mensa: hier fehlt ein Link zu besagter Internetseite.~~
- ~~USZ: s.o.~~
- ~~Neue Einträge "Seminargruppe" und "Studenplan"~~

back:
- Redaktionsschluss anpassen, wenn es soweit ist

Gott, in diesem Dokument müsste man echt mal von Grund auf ausmisten und ne Menge vereinheitlichen...
NoPanic Rewrite 2016? :D

**Comment by lucaswo** [comment]
Habe mal angefangen: 4d98386eeaaa94f2bd3348fdbf2398d2433ddbbe
Glossar und F1 sind überarbeitet und zu den Programmierkursen habe ich einfach nur die Überschrift geändert.

**Comment by mchlnix** [comment]
Das englische No Panic sollte über eine extra Mailingliste eingeleitet werden.  Was daraus geworden ist, müsste einer von euch wissen.

**Comment by kiliankoe** [comment]
Weil die unheimlich produktive Konversationsform einer Mailingliste das einzige ist, was die englische Übersetzung an ihrer Entstehung hindert...

**Comment by mchlnix** [comment]
Es ging ja darum den Prozess anzustoßen. Von mir aus können wir uns danach auch über Rauchzeichen verständigen.

**Comment by sjmielke** [comment]
Und 19 englische Issues sind nicht Anstoß genug? Da hab ich ja doch die bessere Ausrede, nix getan zu haben :D
Ist aber ja auch nicht weiter wild, kann man über den englischen Kram zum nächsten Jahr nochmal nachdenken, wir sollten uns jetzt halt auf den deutschen Teil konzentrieren.
Wenn jetzt alle so rangehen wie @lucaswo haben wir das auch ganz schnell erledigt :blush:

**Comment by Feliix42** [comment]
Ich hab 2-3 Texte als englische Version (teilweise fehlt noch ein Absatz) da. Ursprünglich hatten sich ja mal 4 Leute oder so gemeldet, die das ganze mit machen wollten. Deshalb frage ich mich, wo die sind :D

Dann wird das ganze eben erst nächstes Jahr. :blush:

**Comment by sjmielke** [comment]
Bzgl ZIH: was ist denn da mit den Mailadressen? Bekommen Erstis wirklich noch @mail.zih.tu-dresden.de? War da nicht mal was mit @msx.tu-dresden.de oder so? Oder hänge ich da in irgendeiner längst abgeschlossenen Diskussion hinterher? :D

**Comment by Feliix42** [comment]
Alles dreis. :D
Ab WS 14/15 gibt es ja das neue Schema. Und bei uns funktioniert @mail.zih.tu-dresden.de <http://mail.zih.tu-dresden.de/>, @msx.tu-dresden.de <http://msx.tu-dresden.de/> und @mailbox.tu-dresden.de <http://mailbox.tu-dresden.de/>.

**Comment by kiliankoe** [comment]
mail.zih geht bei euch noch? O.o

Die Mailbox Adresse ist ansonsten ja eh nur ein Alias, die sollte immer gehen.

**Comment by Feliix42** [comment]
Hab es gerade extra noch mal geprüft, geht. :D

Ist vermutlich nur eine Weiterleitung zu msx, aber da ja oft auf das „alte“ Schema zurückgegriffen wird, kann man es ja mal drin lassen.

**Comment by sjmielke** [comment]
Hm okay, wenns bei dir geht, sollte es ja auch bei den neuen Erstis noch gehen... Trotzdem könnte man die msx-Adresse mal dazu erwähnen, damit da keiner verwirrt ist.

**Comment by kiliankoe** [comment]
Die msx Adresse muss auf jeden Fall dazu, die ist ja eigentlich die offizielle afaik (@dirkonet?). Vermutlich sollten wir auch darauf hinweisen, dass die mail.zih Adresse explizit nicht der offizielle Zugang ist, wer weiß wie lang sich das noch hält.

**Comment by Feliix42** [comment]
Genau. Mir fällt spontan noch ein: Sollten wir das neue Selbstbedienung-Portal mit aufnehmen? (http://portal.slm.tu-dresden.de/ <http://portal.slm.tu-dresden.de/>)

**Comment by kiliankoe** [comment]
Ja, bitte!

**Comment by dirkonet** [comment]
@kiliankoe da zu viel kaputtgehen würde, wenn Studierende nicht mehr unter loginname@mail.zih erreichbar sind, wird das hoffentlich noch eine Weile funktionieren, auch für Neuimmatrikulierte.

**Comment by kiliankoe** [comment]
Ah ok, ja gut. Dann weisen wir dennoch die msx Adresse als die offizielle aus und erwähnen den Rest mit.

**Comment by dirkonet** [comment]
Die "offizielle" Adresse ist der Alias Vorname.Nachname[Nummer]@mailbox. Die tatsächliche Mailbox ist loginname@msx.

**Comment by kiliankoe** [comment]
Bäh :P Aber gut, dann richten wir uns bestenfalls komplett nach den ZIH Guidelines :D 

Aber was mach ich jetzt mit meiner Vorname.Nachname@tu-dresden.de Adresse? Wie offiziell ist die denn dann? :P

**Comment by dirkonet** [comment]
Das ist die offizielle Adresse für Mitarbeiter. Die bekommen SHKs/WHKs wahrscheinlich in Zukunft gar nicht mehr. Warum auch immer. Sei also froh, dass du sie hast, und halt dich dran fest, wenn es dir schlecht geht :D

**Comment by sjmielke** [comment]
Ist immer wieder lustig, wenn $leute erstaunt fragen, wie ich denn als mickriger Student an sone Adresse gekommen bin :D

**Comment by Bet-Ty** [comment]
Halli-Hallo! Kann mir mal bitte irgendwer die Berechtigung verschaffen, irgendwas zu pushen? Git sagt mir, dass ich das nicht darf... Oder bin ich nur zu blöd? :(

**Comment by mchlnix** [comment]
Ich finde man sollte die Unterpunkte doch als einzelne Issues aufziehen und mit dem Milestone v_2015 versehen. Habe die englischen Issues nun schon auf v_2016 umgemünzt.

Dann macht die Fortschrittsanzeige wenigstens Sinn und ich krieg nicht dauernd off-topic Kommentare von diesem Issue (nichts für Ungut).

**Comment by Bet-Ty** [comment]
Überarbeitete Helferliste siehe mein pull request (#86)! Das ist echt eine ätzende Vorgehensweise :D

**Comment by kiliankoe** [comment]
Hab dir mal ne Einladung für das no panic Team geschickt, wenn du die annimmst hast du auch die Pushberechtigung ohne für jede Kleinigkeit einen pull request aufzumachen ;)

**Comment by Bet-Ty** [comment]
Supi, danköööö :) (und sorry an alle, die jetzt eine Benachrichtigung bekommen, nur weil ich danke gesagt hab... ^^)

**Comment by Bet-Ty** [comment]
"Alles in allen Richtungen korrekturlesen!" ist erledigt. Ergebnisse siehe meine drei Commits zu "Korrekturen/Vereinheitlichungen". Ablaufplan, Campusplan und Werbung habe ich aber nicht in meine Kontrolle einbezogen.

**Comment by jgonsior** [comment]
Ich befürchte ich habe durch das Hinzufügen des Verleihtextes irgendwie das Layout der FSR Gesichter zerstört - aber das wollte @sjmielke ja sowieso neu machen, oder?

**Comment by lucaswo** [comment]
Im Studienbetrieb steht noch was von 4 SWS Englisch für Diplomer. Wurde das nicht runtergekürzt?

**Comment by jgonsior** [comment]
Sollte man in der NoPanic erwähnen, dass es bald eine aktuellere Version der Bachelor und Diplomer Studienordnungen geben wird?

**Comment by kiliankoe** [comment]
Würd' ich ehrlich gesagt nicht. Ändert nichts für die Leute, die unter den aktuellen Ordnungen anfangen und verwirrt wohl eher bloß falls sie denken, dass sich für sie plötzlich Dinge ändern.

**Comment by foobar0112** [comment]
neuer Ablaufplan erledigt.

**Comment by sjmielke** [comment]
Okay, hier also das, was jetzt noch offen ist:

Global:
- lila Farbe doch nochmal ausprobieren (mach ich gerade)
- neue Werbung
- Vorder- und Rückseite doch nochmal de-schnittkant-ifizieren?
- Schnittkanten? (sind ja scheinbar doch sinnlos, oder?)
- Formatierung... wenn "Redaktionsschluss" ist.

Studienbetrieb:
- Prüfungen austragen: 3 Werktage? Wirklich? Für alle?
- Scheine wirklich erwähnen? Hab ich nie was mit zu tun gehabt.

Erstsemester-Checkliste:
- USZ mal auf die Sache mit der Sporthalle hinweisen, keine Ahnung, wieviel Einfluss das hat.
- Rückmeldung: Zeit so spezifisch?

Modulübersicht:
- Allg. Basisqualifikationen: ist mir neu, dass das eine fixe Veranstaltung ist, ich dachte da kann man sich auch Dinge wählen?

auditorium:
- Ja/Nein?

FSR:
- neue Gesichter (wollen wir das Benutzen der Wahlbilder erzwingen?)

ZIH:
- msx-Adresse erwähnen
- SLM erwähnen (erstpasswortänderung und so vielleicht dazu reinbringen?
- julius' todo

back:
- Redaktionsschluss anpassen, wenn es soweit ist

**Comment by sjmielke** [comment]
Ich wollte eigentlich auch schnellstmöglich nochmal ne Mail wegen der Gesichter auf der FSR-Seite schreiben, ob die Semester alle so stimmen - ist jetzt halt alles eher frei geraten.
Also bitte sonst schonmal drüberschauen und Leute anstoßen, das zu checken :)

**Comment by foobar0112** [comment]
ich finde die Rahmen um die Bilder der FSRler lassen diese wie Todesanzeigen aussehen...
@sjmielke: magst du S1/S2 auf dem Plan markieren?

**Comment by sjmielke** [comment]
Ohne Rahmen... joa, das geht auch, so schlimm siehts nicht aus... Meinungen?
S1/S2 markieren... weiß nicht recht, nur wegen Englisch... Ich bin sehr unentschlossen :D Aber wenn sich niemand dagegen ausspricht, mach ich das die Tage noch.

**Comment by foobar0112** [comment]
ich spreche mich ausdrücklich dafür aus. danke.

**Comment by sjmielke** [comment]
SE1/2 sind markiert.
Weil ich gerade nicht mehr weiß, wo wir drüber gesprochen hatten: der lila Zeitplan ist das erste, was in lila irgendwie echt nicht so doll aussieht, wahrscheinlich so viel so starke dunkle Farbe. Ich hab mal versucht, ein bisschen drin rumzuspielen, aber da verliert man in LibreOffice ja sofort die Lust.
Auch wenns ein bisschen Gefriemel ist, der Zeitplan *muss* nächstes Jahr getext werden - oder zur Not auch getikzt, alles besser als die aktuelle Notlösung.

**Comment by sjmielke** [comment]
Es ist Montag einer neuen Woche - wenn heute noch irgendwas neues dazukommt, okay, ich würde dann aber gerne den Redaktionschluss auf heute Abend setzen.
Die Werbung kann man auch morgen oder übermorgen noch problemlos einsetzen, das ändert bspw. Dinge wie die Formatierung nicht (die man dann morgen final in Angriff nehmen kann). @dirkonet: das sollte dir ja dann auch entgegenkommen, wenn wir jetzt mal nen Schlussstrich ziehen, wenn du dich mitm Textmarker nochmal ran wagen willst (wie auch immer das Dokument dann Menschen erreicht, scannen oder so?).

**Comment by foobar0112** [comment]
Wie ist das nun mit dem Text zu den Flüchtlingen in Dresden und dem USZ (https://fsr.etherpad.ifsr.de/1154) aus? Wo soll der integriert werden? Würde das von der Seitenanzahl nun passen (mit der Werbung) oder weichen wir (auch mit der Afeefa-Werbung) auf das Faltblatt in der Mitte aus?

**Comment by sjmielke** [comment]
Im Moment haben wir 48 Seiten (da wird auch formatierungstechnisch hoffentlich nichts mehr passieren, was das ändert). Dein Text braucht zwei Seiten würde ich so spontan sagen - bekäme man also unter, wenn wir nicht für 50 Seiten plötzlich deutlich mehr bezahlen. Kannst du vielleicht mal mit dem Login oder dem Telefon bei Saxoprint nachforschen, wie das aussieht? In #91 sieht es auch so aus, als wären Umschlag und Inhalt zwei getrennte Sachen, da weiß ich garnicht mehr, wie das letztes Jahr war... die Bestellung sollte halt wirklich zum Ende dieser Woche raus.
Inhaltlich sieht der ja mittlerweile einigermaßen fertig aus - wo meinste denn, würde das Sinn ergeben? Und als was, als normale \section oder nur als \section* irgendwo oder als Appendix oder so? Du kannst das ja mal wie die anderen Texte sauber integrieren und schaun. Eine Sache wird aber vermutlich passieren: bei so vielen Links wird die Linkliste die zwei Seiten ganz verbrauchen und das Fakultätsbild wird wohl rausfliegen...

**Comment by dirkonet** [comment]
@sjmielke: 50 Seiten sind 52 Seiten. Vielfache von 4 und so.

**Comment by sjmielke** [comment]
Ups. Ja. Dann würde ich schon versuchen, bei den 48 zu bleiben und das tatsächlich irgendwie als Faltblatt dazuzulegen. Doppelseitiger A5-Druck, einmal gefaltet oder leicht zugeschnitten sollte ja gut gehen - das können wir doch auch selber machen, oder?

**Comment by foobar0112** [comment]
ja, ich glaube so waren wir auch verblieben. Wenn der Text zwei Seiten braucht, ist nur ide Frage, wo die Afeefa Werbung hinkommt. Man könnte ihn auch noch kürzen. Wenn er eh auf das Faltblatt kommt, dann können die Links ja auch direkt dort rein (vllt sind auch nicht alle so sinnvoll - was meint ihr?), dann gibt es keine PRobleme mit dem schönen Fakultätsbild.

**Comment by sjmielke** [comment]
Genau so würde ich das machen. Also Links ganz klein drauf, falls es wen wirklich interessiert - und für die Werbung kommts halt drauf an, wieviel Platz du der geben willst :D
Aber wenn wir dieses Faltblatt eh selbst drucken, haben wir da ja noch Zeit - beziehungsweise *du* hast Zeit, dir zu überlegen, wie du das am besten gestaltet haben willst :P Getext im Stil der NoPanic? Könnte komisch wirken, dass das dann getrennt ist. Eigener Stil? Könnte komisch wirken, dass es dann in der NoPanic liegt... da sollte man auch nochmal drüber nachdenken. Vielleicht tatsächlich auch so Kleinigkeiten, wie die Links nicht mit arabischen Zahlen durchzunummerieren etc.

**Comment by foobar0112** [comment]
Ja, ich würde schon den Stil der NoPanic nehmen, andererseits könnte man den Text auch auf zwei Seiten verteilen, die Links mit reinnehmen, das Fakultätsbild auf die nächste Seite und die Werbung, das wären dann vier zusätzliche Seiten...

**Comment by jgonsior** [comment]
Das Falten kann man dann auch als weiteres Highlight in das Programm des ESE-Tütenpackens mit aufnehmen!

**Comment by sjmielke** [comment]
@foobar0112: Ich hab jetzt mal was commitet, das würde ich mir als A4-Version in der Hälfte gefaltet und an den Seiten um ein paar Millimeter beschnitten vorstellen - auf die Rückseite könnte dann ne fette Afeefa-Werbung oder so - was hältste davon?

**Comment by sjmielke** [comment]
Andere Sache, die ich gerade noch gemacht hab: die Keys für die Links fand ich gerade, wo ich sie so im Faltblatt gesehen habe schon arg aggresiv auffällig, hab jetzt mal das Lila als Rahmen- und Textfarbe gesetzt und nachdem Grau dafür irgendwie doof aussah, den Hintergrund weiß gelassen.
Wie findet ihr (wer immer "ihr" im Moment noch ist) das?

**Comment by dirkonet** [comment]
Ziemlich extreme Wall of Text. Wie wäre es mit "Heft im Heft", gefaltete A4-Seite, Deckblatt afeefa-Logo, drinnen dann der Text auf die restlichen 3 A5-Seiten verteilt? Dann hat man nur eine A5-Seite Text auf einmal. Die Box für Link VII ist auch breiter als die anderen, soll das so?

**Comment by foobar0112** [comment]
Das Faltblatt finde ich gut, auch die Lösung mit den Fußnoten. Sieht schick aus.

Aber wenn es dann in der Mitte gefaltet ist und nur drin liegt, sieht es wirklich nicht mehr dazugehörig aus, wäre aber auch halb so wild, doch eine so riesige Afeefa Werbung bräuchte es dann vielleicht auch wieder nicht.

Was haltet ihr davon den, zugegeben etwas langen Text auf zwei A5 Seiten aufzuteilen, eine A5-Seite Afeefa-Werbung zu machen und die vierte Seite zum entzerren unseres Layouts zu verwenden? Dann hätte man wieder vier komplett und könnte es ins Heft reinnehmen.

Heft im Heft mit Afeefa vorn sieht dann vielleicht auch wieder komisch aus, so als ob das ein Afeefa-Heft wäre. Ist zwar eine Themengruppe, hat aber prinzipiell ja aber nichts miteinander zu tun...

**Comment by sjmielke** [comment]
Mögt ihr eure Kommentare einfach mal ins gerade erstellte Issue #94 kopieren und dann hier löschen? Das ist groß genug für ein eigenes Issue, fürchte ich...

**Comment by sjmielke** [comment]
Hab nochmal alles großflächig umsortiert ein paar Kleinigkeiten ausgebessert und ganz viel finale Formatierung gemacht, hoffentlich ist jetzt alles bzgl. Doppelseitigkeit und Platz und so optimal. Was nix mit der Doppelseitigkeit zu tun hatte:
  * der Campusplan ist jetzt auf der ersten Innenseite - noch vor dem Inhaltsverzeichnis. Finde ich einfach gut, dass man das Ding direkt aufschlägt und dann links den Zeitplan und rechts den Campusplan hat.
  * der ZIH-Artikel ist ein gutes Stück weiter nach vorne gerutscht. Finde den wichtig, da sollte der nicht als letztes nach so (mal übertrieben gesagt) "netten warum-nicht-Infos" wie dem ascii- und CD-Artikel kommen.

So gefällt mir das doch alles wieder relativ gut. Sind halt vier Seiten mehr, aber okay, es sind keine großen Leerseiten mehr drin.

Was fehlt jetzt noch?
  * USZ-Feldbettbild, um den Flüchtlingsartikel bunter zu machen
  * beide Werbungen
  * Redaktionsschluss anpassen
