### ISSUE TITLE
HTTPS > HTTP

### ISSUE THREAD

**Issue by kiliankoe** [fsr/nopanic#72]
Alle Seiten der TU und des Studentenwerks sollten SSL unterstützen. Ist jetzt nur ne Kleinigkeit, aber es wäre schön hier nochmal kurz durchzugehen, das bei jedem Link zu prüfen und zu ersetzen :blush:

**Comment by mchlnix** [comment]
Bin alle Dateien im `texte` Ordner durchgegangen. 98% sicher alle erwischt zu haben, bei denen es ging.

Alle Links, die Zertifikatsprobleme hatten wurden http gelassen, oder darauf zurück geführt. Also befinden sich noch http Links in den Dateien.

**Comment by kiliankoe** [comment]
awesome :+1:
