### ISSUE TITLE
neuer Campusplan

### ISSUE THREAD

**Issue by frankhedecke** [fsr/nopanic#74]
Auf dem Campusplan steht noch INF anstatt APB.

Sollte SE1/SE2 auch eingefärbt werden?

**Comment by sjmielke** [comment]
Steht im #71 aktuell als fünfter Punkt drin. Der ganze Plan sollte aktualisiert werden.
Findet im SE1/SE2 Kram für die Erstis statt? Dann sollte der dieses Mal auf jeden Fall eingefärbt werden, ja.
@kiliankoe , weißt du noch, wer letztes Mal die Erlaubnis wegen des Plans eingeholt hat? Ich denke, das müssten wir dieses Mal dann ja nicht unbedingt nochmal machen.
http://tu-dresden.de/service/orientierung/lageplaene/plaene/tpcampusss15.pdf würde ich dann auch wieder einfärben.

**Comment by kiliankoe** [comment]
Das hier war unserer "Erlaubnis" von letztem Jahr:

> Lieber Herr Költzsch,
>
>ich denke, dass das kein Problem darstellt. Bitte nutzen Sie den Plan. Im Prinzip stehen ja die Campuspläne der TU auch im Netz, was soll's.


Im Seminargebäude finden vermutlich ein paar Übungen statt, von mehr weiß ich aber auch nicht. Aber ein paar Übungen sind vermutlich auch wieder sonstwo über den Campus verteilt.

**Comment by mchlnix** [comment]
Soll das in schön gemacht werden, oder reicht ein wenig Photoshop?

**Comment by kiliankoe** [comment]
Sebastian hält das wohl am liebsten wieder als Vektorgrafik fest und bastelt sich da vermutlich mit Inkscape einen ab^^

**Comment by sjmielke** [comment]
Bitte bloß auf keinen Fall in Photoshop. Da wirs schon als Vektorgrafik haben, sollte das auf jeden Fall eine bleiben.

**Comment by mchlnix** [comment]
Dann halt ich mich besser raus t(o_ot)

**Comment by sjmielke** [comment]
Das HSZ hat keine Abkürzung mehr und der Willersbau hat jetzt "WILL"? Wat? Naja, ist mal wieder schnell zusammengeinkscapt und dank Font-Blödsinn ist natürlich auch das resultierenden PDF wieder 1.7MB groß... Aber... äh... Pixelgrafiken wären bestimmt noch schlimmer! :P
Achja, commit kommt später.

**Comment by kiliankoe** [comment]
Zumindest im Campus Navigator ist alles noch beim alten.

**Comment by foobar0112** [comment]
In den Seminargebäuden finden die Sprachkurse in Englisch statt, die kann man auch im ersten Semester machen... Ich würde S1/S2 daher auch verzeichnen.
@sjmielke, du hast die Gebäude jetzt grün markiert. Ich weiß nicht, in wieweit die Farben noch auf das Lila des Deckblattes umgestellt werden sollen. Falls ja (also das würde dann Kapitelüberschriften, Verweise, Modulübersicht und Ablaufplan betreffen), dann sollte das auch da sicherlich noch lila werden. ;)

**Comment by lucaswo** [comment]
Ich habe das mit dem lila ausprobiert und es sieht (gerade bei den Linkboxen) grausig aus. @sjmielke hatte da ja auch schon Bedenken geäußert.

**Comment by sjmielke** [comment]
Das lila, was jetzt in der nopanic verbaut ist, hebt sich leider auf dem Plan nicht so gut ab, mit ner etwas saturierteren und helleren Variante gehts aber. Habs mal commitet, aber so richtig gefallen tut mir das an der Stelle nicht...
