### ISSUE TITLE
Falsches Emailschema in zih.tex?

### ISSUE THREAD

**Issue by mchlnix** [fsr/nopanic#75]
Zeile 34: Zugang bekommst du mit deinem Login \textit{sXXXXXXX@tu-dresden.de} und deinem Passwort. Mehr Informationen findest du unter \link{https://tu-dresden.de/zih/dienste/arbeitsumgebung/zugang_datennetz}.

Weiß nicht ob sich da was geändert hat, aber sollte es nicht (wie weiter oben in Zeile 17 erwähnt) `sXXXXXXX@mail.zih.tu-dresden.de` sein?

**Comment by Feliix42** [comment]
Nein. Für eduroam, was ja eine uni-übergreifende Sache ist, ist es `s-Nummer@Uni-Name.de`

**Comment by kiliankoe** [comment]
Jop, das ist an der Stelle keine valide ZIH E-Mail Adresse, sondern der Login. Stimmt so :)

**Comment by mchlnix** [comment]
Alles klar. 'Mit deinem Login' finde ich dann vielleicht ein wenig verwirrend für Ersties (und mich selbst, scheinbar). Aber wenns kein Fehler ist, gut.

**Comment by kiliankoe** [comment]
Es gibt ja auch Leute, die sich nach ihrer Imma so tolle Mailadressen wie sNummer@gmail.com registrieren. Verwirrte Erstis wird's immer geben ;)

**Comment by dirkonet** [comment]
Vielleicht umformulieren in

    Zugang bekommst du mit deinem Login in der Form \textit{sXXXXXXX@tu-dresden.de} und deinem Passwort. Mehr Informationen findest du unter \link{https://tu-dresden.de/zih/dienste/arbeitsumgebung/zugang_datennetz}.
