### ISSUE TITLE
Links in checkliste.tex sind tot.

### ISSUE THREAD

**Issue by mchlnix** [fsr/nopanic#79]
http://www.dresden.de/de/02/or/anliegen/c_233.php ,
http://www.dresden.de/de/02/or/anliegen/c_336.php ,
http://www.dresden.de/de/02/or/anliegen/c_zweitwohnungssteuer
sind tot.

https://github.com/fsr/nopanic/blob/master/texte/checkliste.tex#L35
https://github.com/fsr/nopanic/blob/master/texte/checkliste.tex#L37
https://github.com/fsr/nopanic/blob/master/texte/checkliste.tex#L38

**Comment by Feliix42** [comment]
Gehört zu #71 - Wer das hier fixt, kann bitte gleich die anderen Punkte von der Liste für die Checkliste fixen.

**Comment by kiliankoe** [comment]
Kack Dresden ist mit dem Relaunch von dresden.de nicht auf die Idee gekommen, dass sie ihre alten URLs alle ummappen müssen. Ohne Spaß, das ist so idiotisch.

**Comment by mchlnix** [comment]
Dresden selbst verlinkt das auf ihrer Seite falsch. Hm.
