### ISSUE TITLE
Links in studienbetrieb.tex funktionieren nicht mit https

### ISSUE THREAD

**Issue by mchlnix** [fsr/nopanic#82]
https://sprachausbildung.tu-dresden.de hat Problem mit dem Zertifikat. War schon https.
https://www.tudias.de/de/Sprachschule.html hat Problem mit dem Zertifikat. War schon https.

https://github.com/fsr/nopanic/blob/master/texte/studienbetrieb.tex#L79
https://github.com/fsr/nopanic/blob/master/texte/studienbetrieb.tex#L81

**Comment by kiliankoe** [comment]
Wer kommt denn auf die Idee ein SSL Cert von nem Privatanbieter wie tyclipso.net zu nehmen?!

Bei Zertifikatsfehlern würde ich persönlich lieber auf plain http umsteigen. So lang es Browser gibt, die manche solche Fehler nicht umgehen lassen, müssen wir Erstis ja keine Steine in den Weg legen ;)

**Comment by mchlnix** [comment]
So hab ich das bei allen Links gehalten, die ursprünglich http waren. Wenn allgemein die Devise ist, auf http umzusteigen, wenn https nicht funktioniert, werde ich die beiden links schnell fixen.
