### ISSUE TITLE
Glossar

### ISSUE THREAD

**Issue by frankhedecke** [fsr/nopanic#83]
Bitte den Eintrag  **Helpdesk** hinzufügen.

**Comment by dirkonet** [comment]
Mit welcher Beschreibung?

**Comment by Feliix42** [comment]
Meinst du [das hier](http://tu-dresden.de/die_tu_dresden/fakultaeten/fakultaet_mathematik_und_naturwissenschaften/fachrichtung_mathematik/studium/helpdesk), @frankhedecke?

**Comment by frankhedecke** [comment]
nope. Den ZiH-Helpdesk in der E036 meine ich.

Wenn die Ersties in der FAK rumlaufen werden die von anderen öfter mal gefragt wo der ist, daher sollten die das wissen. Vllt. wollen die ja auch mal dorthin.

**Comment by dirkonet** [comment]
Das Ding heißt Service Desk und ist unter https://tu-dresden.de/zih/ese auch kurz erwähnt.

**Comment by frankhedecke** [comment]
Dann bitte den Eintrag **Service Desk** hinzufügen.
