### ISSUE TITLE
Count Down Text inhaltlich nicht aktuell

### ISSUE THREAD

**Issue by Bet-Ty** [fsr/nopanic#87]
Ich lese ja gerade die gute No Panic Korrektur und schaue auch nach, ob die Infos inhaltlich korrekt sind. Beim Count Down Text scheint das nicht der Fall zu sein! Zum Beispiel heißt es "Bei den Erasmus-Partys hast du jeden Dienstag die Gelegenheit, gemeinsam mit ausländischen Studenten zu feiern und deren Kulturen kennen zu lernen." Aber auf der Homepage vom CD sieht es für mich eher so aus, als wäre dienstags immer Werwolfabend... Haben wir da Kontakt zu jemandem vom CD, der den Text mal den aktuellen Umständen anpassen kann? Ansonsten würde ich einfach aus den Infos auf der Internetseite was zusammenschustern. Ich war aber ehrlich gesagt seit der ESE nicht mehr da, bin also nicht so kompetent :D

**Comment by kiliankoe** [comment]
Bei der Geschwindigkeit, auf die das CD auf Mails antwortet, können wir die Nachfrage so wohl lassen. Anwesenden Menschen im ascii wissen auch nichts genaueres, daher würde ich das einfach mal wegfallen lassen, so lang das CD da auch nichts weiter zu auf der Webseite veröffentlicht. 

Sollten die wieder stattfinden (waren ja sonst wirklich immer Dienstags) nehmen wir das halt in der nächsten Ausgabe wieder auf (so lang jemand dran denkt :P).

Nimm's raus oder pass das dem Kalender an, ist beides gut :+1:

**Comment by Bet-Ty** [comment]
Guddi, ich werde das anpassen! :)

**Comment by jgonsior** [comment]
Laut http://tu-dresden.esn-germany.de/en/laenderparty?language=en findet es weiterhin jeden Dienstag statt, ich würde es drinnen lassen. Jetzt gerade steht wahrscheinlich nichts im Kalender vom CD weil gerade Semesterferien sind, und die erste Länderparty wohl erst Mitte/Ende Oktober stattfinden wird.

**Comment by Bet-Ty** [comment]
Ach okay, das kann natürlich sein! Vielen Dank für den Hinweis. Dann lassen wir es so und ich erkläre dieses Issue für geclosed.
