### ISSUE TITLE
Farben

### ISSUE THREAD

**Issue by kiliankoe** [fsr/nopanic#88]
Farben müssen noch angepasst werden.

Sprich vor allem
```latex
\definecolor{ifsrgreen}{rgb}{0.69, 0.88, 0.11} % 177, 225, 28
```

**Comment by lucaswo** [comment]
https://media.giphy.com/media/X3KNwlvpahFBK/giphy.gif
Vorallem Sebastians Linkmagic müsste dafür angepasst werden, weil schwarz auf lila sieht halt nicht...

**Comment by kiliankoe** [comment]
Also alles grün belassen und nur das Cover lila?

**Comment by lucaswo** [comment]
So war jetzt der Plan. Der Campusplan ist ja jetzt auch grün. Ich hatte das Lila unabhängig von @sjmielke getestet und weder der Campusplan, noch die Links sahen gut aus. Die Überschriften waren ok. (Bild folgt)

**Comment by sjmielke** [comment]
Hitlergifs in Issue Nr. 88, super :D
Auch wenn ich natürlich voll seiner Meinung bin... also @lucaswos.
Aber du kannst es gerne mal ausprobieren Kilian, vielleicht findest du einen erträglichen Farbton und man kann drauf spekulieren, dass der im Druck immernoch ok ist?
Ansonsten... eigentlich stehts ja schon oben drin: `ifsrgreen` und nicht `ese2014green`, von daher isses glaubich schon okay^^

**Comment by kiliankoe** [comment]
Ne, ausprobieren ist beim aktuellen Zeitplan unnütz und impraktikabel, lassen wir das^^ Ist ja auch als FSR Farbe nicht ganz falsch. Ein Bobbel-Bild gibt's ja auch, sprich grün ist eh drin.

Alles gut :+1:

**Comment by lucaswo** [comment]
![scs](https://cloud.githubusercontent.com/assets/7880558/9607069/47bf3b64-50c7-11e5-91f1-7137ace9b5aa.jpg)

fyi

**Comment by kiliankoe** [comment]
Ja ne, wenn dann natürlich weißer Text da drüber, sonst ist klar, dass das kacke ausschaut :D 

Überschriften sind allerdings schon nice^^

**Comment by sjmielke** [comment]
Tatsache, so schlecht siehts nicht aus... Spannend wären auch noch diese Dinge bei der Modulübersicht, dann finde ich, könnte (und sollte) man das machen. Ist ja an sich auch keine große Umstellung.
