### ISSUE TITLE
No Panic Rewrite 2016

### ISSUE THREAD

**Issue by sjmielke** [fsr/nopanic#89]
Ich finde, wir müssten die NoPanic mal größtenteils komplett neu schreiben. Da ist so unglaublich viel Redundanz drin (z.B. die Sache mit den Sprachkursen, die überall so halb steht), anfangs irrelevanter Kram (Studienblätter? Scheine? Also bitte.) und so richtig einladend wirkt so viel Text auch nicht.

Ich würde hier gerne bis v2016 einfach schonmal so ein paar Ideen sammeln, wie man das besser machen könnte, damit es nicht verloren geht, bis sich $leute dann damit auseinandersetzen.

Vorschlag 1: Studienbetrieb, Checkliste, ZIH und Glossar mergen.
Vorschlag 2: Eine neue Kategorie "Ich hab' gehört, dass...", wo Dinge wie "Krankmeldung bei Frau BP" oder "Englisch?" beantwortet werden - bestenfalls aber sowas wie Englisch nicht durch eine erneute Erklärung, sondern durch konkretes Referenzieren eines Abschnitts im neuen Super-Mulitdimensionalen-Glossar aus Vorschlag 1.

(achja, Vorschlag 0 ist natürlich: Jetzt tolle Pläne schmieden, nächstes Jahr doch wieder nur Kleinigkeiten ändern, weil es wieder zu spät losgeht :D )

---

Das Ganze hat natürlich auch was mit Issue #19 zu tun, was ich im Sinn hab, treibt die no panic in die Richtung des "No Bullshit Guide to the ESE and the First Semester". Ich fände es aber immernoch auch keine schlechte Idee, drüber nachzudenken, ob man nach so einem ersten kurzen Teil ein größeres Nachschlagewerk anschließt - es gibt viele Fragen, die nicht direkt was mit dem ersten Semester zu tun haben, aber die trotzdem viele haben: Studiengangswechseln, mündliche Prüfungen, Komplexprüfungen, Vertiefungen, Arbeit schreiben, sowas. Ist aber die Frage, inwiefern das, was wir Leuten da im ersten Semester mitgeben überhaupt noch relevant ist, wenns für diese Leute dann soweit ist :D

**Comment by Feliix42** [comment]
Ich würde einen Rewrite schon toll finden. Vielleicht sollte man mal langsam anfangen, was zu planen, um eine Chance zu haben, halbwegs rechtzeitig fertig zu werden. :D

**Comment by sjmielke** [comment]
Wär nicht blöd :D Lass uns uns mal die Tage im Büro oder im ascii zusammensetzen und ein bisschen drüber sprechen.

**Comment by sjmielke** [comment]
Ideensammlung, was man mit der alten NoPanic noch machen könnte:
* Slogans ("In Farbe! Und bunt!", "Jetzt mit Internet!", "Dein Zugang zum WWW!", "Mit cooler Checkliste!", "Ohne Gimmick!", "Fast werbefrei!", "Limitierte Edition!") auf Titelseite!
* Vorwort kürzen bzw. "hippere" (Zitat Felix) Form versuchen
* Grußwort updaten - möglichst kurz fassen (feste Grenze?)
* Studienbetrieb: prinzipiell gut, aber:
  - Leistungsnachweise und Sprachausbildung haben hier nix verloren -> ggf. ins Glossar schieben
  - Einleitungstext überarbeiten
  - "Studienbetrieb" -> "Was passiert hier eigentlich?" (und 2. Überschrift raus)
* Checkliste:
  - "Mail Account" -> "Anmeldung in der Uni-Infrastruktur", Erstpasswort fettdrucken und alles nach ganz oben schieben
  - "Studienrelevante Dokumente" -> "Das Kleingedruckte"
* Modulübersicht an den Schluss schieben

Ideen für was ganz neues (i.e. was eigentlich gebraucht bzw. erwartet wird) am Whiteboard im Büro.

Grundsätzlich ist vor allem der Tutorenleitfaden ein bisschen eine besser NoPanic "für Erwachsene"...

**Comment by sjmielke** [comment]
Von der Tafel abgeschrieben:

* Was ist das hier? (-> "nur die Checkliste ist erstmal wichtig")
* Checkliste
  - Wohnung / Bafög
  - Erstpasswort / Mail / WLAN
  - Fragen? FSR.
* Campusplan
* Ablaufplan
* FSR? Hilfe? Fragen? (nur hier ggf. auditorium) Mitmachen!
* ascii / CD?
* MInf/Inf, BA/Dipl
  - Modulübersicht eingliedern
* Abkürzungskreuzworträtsel

Glossar (nur im Internet)
* Filter für Abkürzungen
* nur ein tl;dr? Was ist das tl;dr eines Glossars?

Begriffe
* VL, Ü, P,  LV -> Module -> Prüfung (Klausuren) + Einschreibung (das ggf. aus Tutorien streichen)
* vielleicht auch einiges aus dem Tutorenleitfaden adaptieren?

NoPanic einzeln ausgeben, nicht im Beutel
* höherer Stellenwert -> wird eher gelesen
* oder einfach in den Tutorien mehr als drauf hinweisen?

**Comment by Feliix42** [comment]
## Wohin gehe ich als Ersti mit meinen Fragen? _(F1 for help)_

- FSR
- auditorium
- Seminargruppenmentoren
- Mund aufmachen! (Dozenten, Kursassistenten, Tutoren, ...)
- Studiengangsberater
- Bafög-Beratung
- StuRa (Sozialberatung usw.)
- Kommilitonen
- ascii?
- StuWe
- Prüfungsamt (was war das? 😄)

**Comment by sjmielke** [comment]
Der Plan für die NoPanic 2016:

Seite(n) | Inhalt
--- | ---
1 | Cover
2 | Wochenplan
3 | Checkliste **kurz** (Stichpunkte)
|
4 | Inhaltsverzeichnis
5 | s/Vorwort/"Was ist das"/ <br /> → bisschen lockerer halten, halbe Seite anstreben
6 | Grußwort <br /> → anderthalb Seiten anpeilen
7-13 | Hilfe? Fragen? Wohin kann ich gehen (siehe Post über dem hier)? <br /> ⇒ FSR, auditorium, Mund aufmachen <br /> → hierarchisch mit Links am Anfang
14-17 | Checkliste **ausführlich** (also einfach die alte)
18-21 | Anpreisung Fak <br /> ⇒ Teich, Wiese, Sitzplätze, Ascii, Spieleabend, ...
22-24 | Def. Module / Studienalltag
25-33 | Modulübersicht (existiert bereits \o/)
34-42 | Glossar
43-44 | Links
|
45 | Kreuzworträtsel (Abkürzungen und Begriffe lernen)
46 | Campusplan
47 | Karlchen und Namen der Tutoren (und Scherzhinweise? was haben wir damit gemeint...)

Die Seitenzahlen sind natürlich größtenteils nur Ideen, aber Anfang und Ende sollten schon exakt so sein.
