### ISSUE TITLE
Werbung 😱

### ISSUE THREAD

**Issue by kiliankoe** [fsr/nopanic#90]
Ich mach hier mal schnell ein eigenes Issue für...

Ich vermute mal hier ist bisher nicht wirklich was passiert, oder? Mail an Trans4mation (und Citrix?) sollte bestenfalls wohl heute noch raus mit der Frage, ob wir das einfach nochmal genauso machen können wie letztes Jahr. Oder hat da schon jemand geschrieben?

**Comment by kiliankoe** [comment]
Laut @kalinni gibt's da ja noch den Binomi Verlag. Was sich logischerweise nach wie vor anbieten würde.

**Comment by sjmielke** [comment]
Haben wir da was konkretes? Oder hat denen schonmal wer ne Mail dazu geschrieben? Oder mag das wer ≠ ich tun?

**Comment by kalinni** [comment]
Zuständig sind eigentlich Ben und Nico, wobei Nico jetzt 3 Wochen im Urlaub ist und Ben durch seine notorische Unerreichbarkeit glänzt.
Ich bin schon dabei und versuche an Infos ran zu kommen - binomi hatte ja in der Anfrage sogar schon mal eine Anzeige mitgeschickt (liegt auf dem Server, ist echt....jaaaaa wunderschön. :D ) aber Nico erinnert sich nicht mehr, ob da schon alles wegen Preis geklärt war und kommt nicht so richtig in sein Postfach rein. Ich kümmer mich drum und versuch das heute noch alles irgendwie raus zu finden, sonst schreib ich noch mal neue Mails...

**Comment by kalinni** [comment]
Hab jetzt bei binomi und communardo noch einmal nachgefragt, mit dem hinweis, dass es recht dringen ist...

**Comment by sjmielke** [comment]
Binomi ist ja da und auch eingebaut, Afeefa... kommt da noch was oder belassen wir es bei der wunderschönen minimalistischen Anzeige, die gerade drin ist?

**Comment by foobar0112** [comment]
ja zur Not nehmen wir die würde ich sagen, aber ich habe großes Vertrauen darin, dass ich heute noch etwas commiten kann... wann wird gedruckt? :P

**Comment by sjmielke** [comment]
Da ich ab gleich erstmal wieder so garnicht erreichbar bin bis Montag morgen... ich wuerde ganz gerne dann alles fertig haben, nur nochmal drueberschauen, das Redaktionsschlussdatum anpassen und das Ding dann irgendwo (ueber HTTP \o/) hochladen, sodass @foobar0112 es dann bei Saxoprint einreichen kann - und es dann nicht allzu lang nach mir in Dresden ankommt :) Irgendwer meinte ja mal man sollte so mit 1-2 Wochen rechnen, dann haetten wir da ja noch ne knappe Woche Spielraum, wenn wir das am Montag schaffen.

**Comment by foobar0112** [comment]
Hört sich nach einem Plan an, dann kann am WE noch der Feinschliff passieren. Klingt gut.

Genau, es wäre wichtig, dass du es baust... :D

**Comment by foobar0112** [comment]
Afeefa ist nun da.

**Comment by sjmielke** [comment]
Dann bitte auch hochladen ;)

**Comment by foobar0112** [comment]
**Nun** ist Afeefa da.

**Comment by sjmielke** [comment]
Da ist Afeefa nun. Und es ist eine einzige große Pixelgrafik... seufz^^ Aber dann hätten wirs ja jetzt.
