### ISSUE TITLE
Bestellung bei Saxoprint

### ISSUE THREAD

**Issue by kiliankoe** [fsr/nopanic#91]
Da Saxoprint (wie ich eben gesehen habe) wohl mittlerweile alte Aufträge aus der Auftragsübersicht löscht (why?!), hier mal die Details der Bestellung von letztem Jahr:

<img width="946" alt="screen shot 2015-09-03 at 11 12 54" src="https://cloud.githubusercontent.com/assets/2625584/9654731/e6cb8fa8-522c-11e5-801d-015b1ad07133.png">

Je nachdem wann die Bestellung rausgeht kann ich mich jedoch leider nicht darum kümmern (bin ab Montag nur noch per Handy erreichbar und unterwegs), daher gebe ich Zugangsdaten für Saxoprint natürlich gerne weiter (@sjmielke @kalinni @foobar0112 ?).

**Comment by sjmielke** [comment]
Ich weiß halt nicht ob und wenn ja wie gut ich mit denen telefonieren kann (denn dazu wird es ja vermutlich wieder kommen...).
Kann das aber gerne versuchen, hochzuladen und dann mal zu schaun (und ggf. halt Katjas Telefonnummer dann hinterlegen^^).

**Comment by sjmielke** [comment]
Ah, wir sollten auch (am besten direkt hier) nochmal kurz drüber sprechen, ob wir nun diese Profi-Datencheck mal dazunehmen wollen oder nicht (die empfehlen uns dann wieder die Schnittkanten, ich sehs schon kommen^^)

**Comment by kalinni** [comment]
Ich bin aber bis Mittwoch auch im Urlaub...

**Comment by lucaswo** [comment]
Mittwoch geht noch, der Druck dauert mit hin und her ca. 7 Tage.

**Comment by sjmielke** [comment]
Noch was, was man in ner Mail an die Liste schreiben könnte, wer so da ist. Ich behalts mal im Hinterkopf für heute Abend.

**Comment by kiliankoe** [comment]
Gegen den Profi-Datencheck. Hat die letzten Jahre auch ohne geklappt (das mit den Schnittkanten wär hier ja jetzt doch kein Problem :P) und den *Gutschein* ist ja eh nicht ;)

**Comment by kalinni** [comment]
eventuell bin ich dann auch danach noch mal ein paar Tage spontan weg. Schauen wir mal, klappt schon irgendwie.

**Comment by foobar0112** [comment]
sind die Zugangsdaten für irgendetwas gut? Ich könnte auch mit denen telefonieren, wenn ich weiß worum es geht...

**Comment by kiliankoe** [comment]
Zugangsdaten für unseren Kundenaccount, unter dem bestellt wird. Wir sind ja "Frau Kostenstelle 111061G" :P

**Comment by sjmielke** [comment]
@foobar0112: Hattest du mal nachgefragt, wie das preismäßig aussieht (gerade im Hinblick darauf, dass wir jetzt ja wies aussieht 4 Seiten mehr haben)?

**Comment by kalinni** [comment]
@sjmielke: Das mit dem Text ist aber keine afeefa-Sache, der kommt von uns. Und die afeefa-Werbung wäre genau eine Seite...

**Comment by sjmielke** [comment]
Vielleicht blöd ausgedrückt: ich meinte den Preis, den wir dann für den Druck hinlegen - gerade weil ich mir bei dem lustigen Blödsinn mit den Tassen vorstellen könnte, dass es auch bei Saxoprint spannende arbiträre Grenzen gibt, was wieviele Seiten kosten.

**Comment by foobar0112** [comment]
nein habe ich noch nicht, mache ich sogleich

**Comment by sjmielke** [comment]
Passt. Sitzt jemand von uns hinter strukturer@ oder ist es problematisch, wenn ich da wen von uns hinter setze?
