### ISSUE TITLE
Kleinigkeiten

### ISSUE THREAD

**Issue by dirkonet** [fsr/nopanic#92]
Ich lese gerade mal die PDF, Stand Commit 1429065, durch. Meine Notizen:

* ~~Seitenzahlen: Cover ist Seite 1? Soll das so?~~ ja
* Seite 2: ~~"Sofern nicht anders angegeben, finden alle Veranstaltungen in der Fakultät Informatik" -> im Andreas-Pfitzmann-Bau~~ → angepasst
* Seite 5:
  * ~~deutscher Plural von Party ist das unerträglich aussehende Partys~~
  * ~~Laut http://www.exmatrikulationsamt.de/clubs sind es anscheinend nur noch 15 Clubs – und hat der KNM überhaupt eine Location aktuell oder existiert der nur virtuell?~~
  * ~~Count Down mit Leerzeichen~~
  * ~~"vom ASCII" -> des ascii~~
  * ~~Kommas zwischen versuchen und doch, zwischen Hochschulgruppen und die~~
* Seiten 6-8: ~~Ist das aktuell? ;)~~ --> ja
* Seite 9:
  * ~~Kein Komma hinter Schule~~
  * ~~Stundenplan: Der Text ist noch aus der Zeit vor den Seminargruppen, oder? ;)~~
  * ~~Vorlesung: Komma hinter ratsam~~
* Seite 10:
  * ~~Übungen: Komma zwischen erwartet und dass~~
  * ~~Praktikum: in den Semesterferien -> in der vorlesungsfreien Zeit~~
  * ~~Komma zwischen empfehlenswert und Praktika~~
  * ~~Komma zwischen Möglichkeit und die (bereits Seite 11)~~
* Seite 11:
  * ~~erwähnte Sebastian ja schon mal, aber ich glaube, Leistungsnachweise/Scheine gibt's nicht mehr~~
  * ~~die Sprachausbildung ist nicht direkt von der TU Dresden, also vielleicht besser "an" der TU Dresden schreiben~~
  * ~~das mit den Kosten für die Sprachkurse hab ich noch nicht ganz verstanden. Ich hab auch nach Ende meines Budgets noch einen kostenlosen Kurs besuchen können.~~

Und natürlich wieder einmal die Schusterjungen, Hurenkinder und so. Seite 12 ist aktuell zum Beispiel recht leer.

Jetzt speicher ich hier erstmal ab und mach im nächsten Kommentar weiter.

**Comment by dirkonet** [comment]
* Checkliste:
  * Wohnung: 100MBit/s hat man mittlerweile auch außerhalb der Wohnheime (und außerhalb von Löbtau/Striesen), haben die Wohnheime nicht zum Teil Gigabit-Anbindung?
  * Mail Account: -> ZIH-Konto? "am besten" streichen, geht nur dort.
  * E-Meal Karte: Bindestrich vor Karte, auch im Text, Bindestrich vor Bescheinigung
  * Sprachkurse: Bindestrich vor Master
  * Sportkurse: \ldots statt drei Punkten?
  * Wohnung: Leerzeichen vor beantragen
  * BAföG Antrag: Bindestrich vor Antrag
  * Bibliotheksausweis: Eventuell noch Hinweis auf benötigte Dokumente (Wohnsitznachweis, z.B. über Ausweis oder Meldebescheinigung)
  * Programmierkurse: Bindestrich hinter C
  * Rückmeldung: Weder Termin noch Rückmeldung stehen auf den neuen Bögen, nur online.

**Comment by jgonsior** [comment]
Laut http://www.studentenwerk-dresden.de/kultur/studentenclubs.html gibt es 16 Studentenclubs?

**Comment by dirkonet** [comment]
Wir sollten vielleicht nicht unbedingt mit Zittauer Clubs werben ;) Tharandt ist ja schon grenzwertig.

**Comment by lucaswo** [comment]
Ich bin gerade dran. commit kommt in ca. 15 bis 30 min

**Comment by jgonsior** [comment]
@lucaswo hast du meinen Commit bereits gesehen? Das Meiste von Dirks erstem Kommentar habe ich bereits umgesetzt. Du darfst aber gerne den Rest machen.

**Comment by lucaswo** [comment]
ahh merge conflict

**Comment by kiliankoe** [comment]
Anmerkung von Dirk:

>  fügt mal noch sNummer für ZIH-Login ins Glossar ein und schreibt das überall so, steht manchmal als S-Nummer drin und verleitet dann zum großen S, wie es auch auf den Bögen für die erstis abgedruckt ist und hisqis verwirrt

**Comment by lucaswo** [comment]
Sooooo. Habe mich mal ausgetobt.

**Comment by foobar0112** [comment]
Der Text soll wohl noch entweder rein, oder wenn's von der Gesamtseitenanzahl her nicht passt als Flugblatt rein: https://fsr.etherpad.ifsr.de/1154.

**Comment by foobar0112** [comment]
- Seite 4: Ich würde "Dank an" statt "Danke an" schreiben
- Link [0] würde ich gern gegen http://drogenlied.de.vu austauschen
- Seite 14: Bildunterschrift unterm xkcd ist durch Blocksatz so breit gezerrt.
- Seite 23: (Press F1 for help) der Abstand über Serviceleistungen des Studentenrates (StuRa) scheint zu groß zu sein
- Seite 25: (auditorium) man könnte das nichtssagende Logo links oben einsparen und dadurch mehr Platz für Text gewinnen, den man braucht um alles auf einer Seite zu belassen, wenn man den Screenshot auf die volle Breite zieht, was ich besser fände.
- Seite 26: "Wer ist der FSR?", müsste man nicht "Was?" fragen?
- Seite 29: Rahmen um die Bilder sind unnötig (schon mal angebracht)
- Seite 30: kommt das aktuell nächste Spieleabenddatum noch mit drauf?
- Die xkcd-Bildunterschriften sind kursiv, alle anderen (wenn denn vorhanden) nicht. alle nicht-kursiv ist einheitlicher.
- Bei den Bildern ohne Unterschrift könnte man noch eine ergänzen - die Frage, wie sinnvoll das wäre (S.14: "417 Studenten langweilen sich bei der Ansprache des damaligen FSRs von 2013". (2013?), S.25: "Auch wenn man auditorium nicht nutzt, lohnt sich der Besuch der Seite zur Bewunderung des GUI-Designes.", S.27: "In familiärer Atmosphäre bereiten extra dafür geschulte Tutoren euch in übersichtlichen Gruppen auf euren ganz individuellen Studienalltag vor.", S.31: "Frank.", S.33: "Das Logo des ASCII - damals zur Gründung im Juni 1963 war diese Codierung noch hoch aktuell...") - doch, wenn ich es mir so überlege, durchaus sinnvoll!

**Comment by kiliankoe** [comment]
> Link [0] würde ich gern gegen http://drogenlied.de.vu austauschen

Das steht nicht zur Debatte. Zombo.com ist die Startseite des Internets.

**Comment by sjmielke** [comment]
> Seitenzahlen: Cover ist Seite 1? Soll das so?
An sich hast du recht, das klingt nicht sinnvoll. Aber: LaTeX erwartet, dass die rechte Seite eine ungerade Seitenzahl hat - entsprechend werden die Ränder konfiguriert. Man könnte also einen Shift um -2 machen, dann wäre der Zeitplan auf Seite 0 und das Cover halt auf Seite -1. Klingt nicht so schlecht, aber es ergibt sich dabei noch ein andere (in meinen Augen) Problem: ich hasse es immer, wenn PDFs Magie mit den Seitenzahlen machen, denn wenn mir mein PDF-Viewer nun irgendwas anzeigt, weiß ich nie, in welcher Relation diese Nummer nun zu dem Nummern, die vielleicht im Text referenziert werden, steht - kommt dann immer auf den Viewer, das Textsatzprogramm usw. an. Und da wir die no panic ja auch online anbieten...
Kann man aber natürlich nochmal drüber reden, ganz abgeneigt wäre ich diesem -2-Shift nicht.
(Oder man würde halt das Kommando, was die pagenumbers printet modifizieren, aber das klingt irgendwie schon nach ner ganz blöden Idee.)

**Comment by sjmielke** [comment]
> Seite 4: Ich würde "Dank an" statt "Danke an" schreiben

Ich glaube das zweite ist da schon auch okay, wenn man sich ganz blasse Anführungszeichen oder so um das »Danke« vorstellt.

> Link [0] würde ich gern gegen http://drogenlied.de.vu austauschen → ok... :disappointed:

But... but... everything is possible! At Zombocom! Hat Kilian schon alles zu gesagt :)

> Seite 14: Bildunterschrift unterm xkcd ist durch Blocksatz so breit gezerrt.

Mmh, aber wenn mans nur linksbündig macht, siehts irgendwie auch nicht so toll aus. Was ganz nett aussieht, wie ich finde, ist den Text links und den Links dann drunter rechts zu haben. Hab ich mal so geändert, schaus dir mal an.
Wäre dann vielleicht auch ne gute Idee, das bei den anderen xkcds genauso rechts abzusetzen? Ich fänds nicht schlecht.

> Seite 23: (Press F1 for help) der Abstand über Serviceleistungen des Studentenrates (StuRa) scheint zu groß zu sein

Gut beobachtet, da waren oben noch manuelle linebreaks. Auch wenn man vielleicht so nochmal überlegen könnte, ob man da nicht den Platz anders verteilen will...

> Seite 25: (auditorium) man könnte das nichtssagende Logo links oben einsparen und dadurch mehr Platz für Text gewinnen, den man braucht um alles auf einer Seite zu belassen, wenn man den Screenshot auf die volle Breite zieht, was ich besser fände.

Ich finde das Logo eher fast noch wichtiger als den Screenshot, zum einen weil die Überschrift schon so nichtssagend ist und das Logo das etwas auf den Punkt bringt und zum anderen, weil die Erstis ja selbst sehen sollen, wie das Ganze aussieht ;) (und sieht das auditorium überhaupt noch so aus wie auf dem Screenshot? Keine Ahnung.) Meinungen?

> Seite 26: "Wer ist der FSR?" - müsste man nicht "Was?" fragen?

Haste recht, klingt besser.

> Seite 29: Rahmen um die Bilder sind unnötig (schon mal angebracht)

Ich bin nicht so ganz überzeugt, dass es ohne besser ist, auch wenn es so schlecht nicht aussieht. Meinungen?

> Seite 30: kommt das aktuell nächste Spieleabenddatum noch mit drauf?

10.05.2015: Montag in der ESE ;)

> Die xkcd-Bildunterschriften sind kursiv, alle anderen (wenn denn vorhanden) nicht. alle nicht-kursiv ist einheitlicher.
    Bei den Bildern ohne Unterschrift könnte man noch eine ergänzen - die Frage, wie sinnvoll das wäre (S.14: "417 Studenten langweilen sich bei der Ansprache des damaligen FSRs von 2013". (2013?), S.25: "Auch wenn man auditorium nicht nutzt, lohnt sich der Besuch der Seite zur Bewunderung des GUI-Designes.", S.27: "In familiärer Atmosphäre bereiten extra dafür geschulte Tutoren euch in übersichtlichen Gruppen auf euren ganz individuellen Studienalltag vor.", S.31: "Frank.", S.33: "Das Logo des ASCII - damals zur Gründung im Juni 1963 war diese Codierung noch hoch aktuell...") - doch, wenn ich es mir so überlege, durchaus sinnvoll!

Konsolidieren ist ne gute Idee (es geht da konkret um das Foto der Fakultät unter dem Grußwort und die Unterschrift des OSM-Screenshots fürs Countdown, die habe ich jetzt kursiv gemacht (ich denke, wir sollten die schon vom "sinnvollen" Fließtext abheben). Im Übrigen sollte man dieses small-textit-rumgeformatiere lieber irgendwie in die captions reinfriemeln - müsste man sich mal irgendwann anschauen.
Was die weiteren Bildunterschriften angeht... die no panic ist ja eher locker lustig formuliert, aber ich glaube das ist zuviel des Guten - sowohl von der Textmasse als auch von der Inhaltsleere - weniger ist mehr und so. Aber vielleicht sehen das ja alle anderen auch anders?

Müssen wir jetzt bloß mal schaun, was da an Meinungen überhaupt noch reinkommt, wo alle irgendwie weg sind - ich bin die nächsten zwei Tage auch erstmal wieder so garnicht erreichbar.

**Comment by sjmielke** [comment]
Hat da echt niemand sonst noch ne Meinung zu? Dann bleibt also einfach alles erstmal, wie es ist und das Ding geht halt so in den Druck....

**Comment by foobar0112** [comment]
Ich habe meine Meinung ja schon kundgetan. 

Die Bildunterschriften finde ich auch so besser, wie du sie gemacht hast, das ziehe ich überall mal nach.

Ich finde den auditorium-Screenshot so jedenfalls doof, entweder größer damit lesbar, oder raus, da haben wir auch keinen großen Verlust mit.

Alternativ könnte man die Bilder nicht mit einem Rahmen versehen, wie eine Todesanzeige, sondern z.B. grau (oder lila) hinterlegen.

**Comment by dirkonet** [comment]
Das FSR-Logo ist auch zumindest in meiner Druckversion recht klein geraten und der CD-Kartenscreenshot wirkt recht kontrastarm.

Ich würde dann sobald @foobar0112 mit seinen Änderungen durch ist mal anfangen, meine heute noch gefundenen Tippfehler zu korrigieren.

**Comment by sjmielke** [comment]
> Ich finde den auditorium-Screenshot so jedenfalls doof, entweder größer damit lesbar, oder raus, da haben wir auch keinen großen Verlust mit.

Ohne ist die Seite so leer... ich würde das jetzt einfach mal so lassen und gut is, vielleicht kann man sich da ja nächstes Jahr mal nochmal mit den auditoriums-Leuten unterhalten - aber da will ich ja eigentlich eh alles anders und übern Haufen geworfen haben... :D

> Alternativ könnte man die Bilder nicht mit einem Rahmen versehen, wie eine Todesanzeige, sondern z.B. grau (oder lila) hinterlegen.

Hatte ich auch schonmal überlegt, aber zum einen kann ich natürlich auf meinem primitiven Laptopmonitor überhaupt nicht einschätzen, wie dunkel das grau wird und irgendwie finde ich selbst auf dem Monitor keins, was mir so richtig gut gefällt... aber ich commite und pushe mal eins, kannste dir ja mal schauen.

**Comment by dirkonet** [comment]
Achso, eine Frage noch: Aktuell ist nur die Vorderseite der No Panic pixlig-texturiert, die Rückseite glatt lila. Soll das so?

**Comment by sjmielke** [comment]
Jop, finde ich so an sich ganz sinnvoll - war ja letztes Jahr auch schon so.
Das kleine FSR-Logo hingegen hat mich auch erst gestört, ein bisschen größer wäre das vielleicht nicht schlecht. Das Logo ist halt mit fetten Rahmen eingereicht worden, nehme ich mal an und jetzt nutzt halt jeder die Version...

**Comment by foobar0112** [comment]
- ja gut, das mit den Bildunterschriften hat sich ja dann doch schon erledigt: alle die da sind, sind kursiv und auch nicht hässlich verzerrt. schön.
- auditorium: ja ok, dann nächstes Jahr :P
- das Grau finde ich gut
- FSR-Logo: größer wäre schon schön

**Problem**: Wenn die Überschrift `6. Semester` auf die neue Seite soll, dann passt das xkcd nicht mehr drunter. :scream:

**Comment by sjmielke** [comment]
Nachtrag zum auditorium-Screenshot: ich habs jetzt doch ungefähr so gemacht, wie du vorgeschlagen hast. Sieht so tatsächlich besser aus, finde ich. Was meinst du, @foobar0112 ?

**Comment by foobar0112** [comment]
ja, doch, sieht ganz gut aus. Ich hatte es auch nicht ausprobiert. Schön :) 

Allerdings passt der Text jetzt nicht mehr ganz auf die Seite. Lösungsvarientan: Logo raus nehmen, Bild kleiner machen (wieder wie vorher, wäre ja aber auch sinnlos), Text kürzen. Schaust du dir das an, @sjmielke?

**Comment by sjmielke** [comment]
Öhm, wo passt welcher Text nicht?

**Comment by foobar0112** [comment]
wenn ich die aktuelle Version baue, läuft das Auditorum um eineinhalb Zeilen über.

**Comment by sjmielke** [comment]
Spannend, bei mir nicht. Hast du das kleiner geschnittene Bild auch wirklich runtergezogen? Mal alles cleanen und neubauen vielleicht?

**Comment by foobar0112** [comment]
ja, es ist alles up to date, meinst du eine der beiden auditorium-Grafiken? Die sind beide aktuell... seltsam. Hast du sie gepusht? :P

**Comment by sjmielke** [comment]
Der Screeshot sollte vorwenigen Stunden geändert worden sein und nun nur noch 748px hoch sein. Alle Fonts auch richtig installiert und so? Magst du mal mal im Slack oder so dein pdf schicken?

**Comment by sjmielke** [comment]
Joschkas Überschriften fangen weiter unten an als meine. Unsere xetex-versionen unterscheiden sich minimal. Das kann doch wohl nicht wahr sein. Mag das bitte nochmal jemand anders kompilieren und schauen, was da rauskommt?

**Comment by dirkonet** [comment]
Auditorium ist bei mir auf einer Seite.
```
$ xelatex --version
XeTeX 3.14159265-2.6-0.99992 (TeX Live 2015)
kpathsea version 6.2.1
Copyright 2015 SIL International, Jonathan Kew and Khaled Hosny.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the XeTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the XeTeX source.
Primary author of XeTeX: Jonathan Kew.
Compiled with ICU version 55.1; using 55.1
Compiled with zlib version 1.2.8; using 1.2.8
Compiled with FreeType2 version 2.5.5; using 2.5.5
Compiled with Graphite2 version 1.2.4; using 1.2.4
Compiled with HarfBuzz version 0.9.40; using 0.9.40
Compiled with libpng version 1.6.17; using 1.6.17
Compiled with poppler version 0.32.0
Using Mac OS X Core Text and Cocoa frameworks
```
