### ISSUE TITLE
Ablaufplan ESE-Kino

### ISSUE THREAD

**Issue by frankhedecke** [fsr/nopanic#93]
Das ESE-Kino beginnt erst 19:00 Uhr.

Im Plan sieht es nach 18:30 Uhr aus.

**Comment by kalinni** [comment]
Der Plan stimmt allgemein nicht, Mittwoch die Vorträge fangen viel eher an und sind 10:45 schon zu Ende, dann ist Taschenausgabe. Zum Beispiel. Das steht so auch schon im Plan im wiki - allerdings ist der Plan im Wiki eventuell trotzdem nicht hundertprozentig korrekt, muss mir den Montag noch mal anschauen, wegen den Raumänderungen, ich sag hier Bescheid, wenn der im Wiki stimmt.
Dann muss wer auch immer zuständig ist, nicht zweimal basteln. :)

Außerdem würde ich am Dienstag das
"Einschreibung
und ewiges
Frühstück

Vorträge

...."

in

"Ewiges Frühstück

Einschreibung

Vorträge

..."

ändern. Ist ja wirklich alles parallel.

**Comment by kiliankoe** [comment]
@foobar0112 Bitte mal dein Datumsformat von LibreOffice anpassen, das kann man so nicht lassen :D

**Comment by foobar0112** [comment]
what? ja, ne das kann nicht sein... - und ist bei mir auch nicht so... aaah die aktuelle PDF hat @sjmielke wohl exportiert. ;)
sonst ist der Plan dem Wiki entnommen, ja @kalinni, würde ich auch so sagen, wenn der fix ist, dann passe ich den Plan nochmal an, ist sonst doppelt gemacht.

**Comment by kalinni** [comment]
Sooo, bin leider eher nicht dazu gekommen, aber jetzt stimmt der Kram im Wiki hoffentlich.
Fühlt euch alle eingeladen, noch mal drüber zu schauen.
Hab Montag den Raum korrigiert und außerdem Montag und Mittwoch Frühstück auf nur bis 9:45 angesetzt.
An beiden Tagen haben wir im Vergleich zum letzten Jahr etwas Zeitdruck nach hinten raus, Montag haben wir den Hörsaal nur in der 2.DS und Mittwoch ist ja um 11 die Taschenausgabe. Da müssen wir jeweils pünktlich anfangen....
Grüße von der Nordsee! :)

**Comment by foobar0112** [comment]
Danke; ich passe es heute im Laufe des Tages an.
Wann soll es in den Druck gehen?

**Comment by foobar0112** [comment]
Ich hoffe, ich habe im Sinne der Wiki-Tabelle den Plan angepasst. 
Auch die Farben sind nun etwas aufgehellt. 
Bitte schaut noch einmal drüber.

**Comment by kiliankoe** [comment]
Wo findet das ESE-Kino eigentlich statt? Der Plan lässt auf die Fak deuten, aber vermutlich ist das ja im KiK, oder?

**Comment by sjmielke** [comment]
@Datumsformat: wieder was dazugelernt, das Format in einem Dokument nutzerspezifisch zu rendern ist auch wieder sone Sache, die allenfalls auf den ersten Blick gut klingt... deshalb: definitiv und dringend Zeitplan in LaTeX nächstes Jahr^^

**Comment by sjmielke** [comment]
Ist das jetzt alles richtig und geklärt? Dann mache ich das Issue nämlich mal zu.

**Comment by frankhedecke** [comment]
Das ESE-Kino findet im Kino im Kasten statt. Treffen ist auch dort.

**Comment by sjmielke** [comment]
@foobar0112: dann bitte noch kurz entsprechend einpflegen und wieder rausrendern :)

**Comment by kalinni** [comment]
Der Montag hat immer noch den falschen Raum, die Taschenausgabe der Stadt Dresden würde ich (am besten mit grauem Hintergrund wegen externe Veranstaltung) am Mittwoch mit aufnehmen, und ansonsten glaube ich, dass es schlau wäre, dass das Frühstück auch in diesem Plan entsprechend dem Wiki am Montag und Mittwoch nur bis 9:45 geht. Sonst kommen dann Erstis 10 Minuten bevor der nächste Part los geht und denken, sie können noch schnell was essen. Wir brauchen die Zeit aber, um in den Hörsaal zu kommen bzw um für die Vorträge aufzuräumen und haben wie gesagt an beiden Tagen etwas Zeitdruck...

**Comment by kalinni** [comment]
Oh man. Seh ich hier nen veralteten Plan?
Weil wenn nicht, sind da noch mehr Fehler: Der Spieleabend Montag findet NICHT im Countdown sondern in der INF statt. Und "Treff im Foyer" gilt für das ESE-Spiel, weil wir die E023 da vorher bestimmt schon wieder in ein Stuhllabyrinth verwandelt haben, nicht für die Schnitzeljagd - da lassen sich die Gruppen tendenziell besser mit Mikros gemütlich in der E023 aufteilen.
(wobei ich zugebe, dass letzteres nicht im wiki steht...)

**Comment by foobar0112** [comment]
habe all deine Anmerkungen angepasst

**Comment by jgonsior** [comment]
Wenn ich mir den Zeitplan hier https://github.com/fsr/nopanic/blob/master/img/zeitplan.pdf anschaue steht aber schon am Montag Count Down und nicht APB drinnen?

**Comment by kalinni** [comment]
joschka hat noch nicht gepusht. ;)

**Comment by sjmielke** [comment]
Hat die Clubwanderung noch anderes Spacing? Sieht so aus...

**Comment by foobar0112** [comment]
Ja hat sie, aber nur damit es auf eine Zeile passt.

**Comment by sjmielke** [comment]
Okay, ich würde es an der Stelle trotzdem umbrechen, aber is ja auch egal. Ich meinte an sich aber auch eher das Vertikale, das hat ja nix mitm Umbruch zu tun.

**Comment by foobar0112** [comment]
Adlerauge
