### ISSUE TITLE
Das Faltblatt - Flüchtlingstext USZ

### ISSUE THREAD

**Issue by sjmielke** [fsr/nopanic#94]
@foobar0112: Ich hab jetzt mal was commitet, das würde ich mir als A4-Version in der Hälfte gefaltet und an den Seiten um ein paar Millimeter beschnitten vorstellen - auf die Rückseite könnte dann ne fette Afeefa-Werbung oder so - was hältste davon?

**Comment by dirkonet** [comment]
Ziemlich extreme Wall of Text. Wie wäre es mit "Heft im Heft", gefaltete A4-Seite, Deckblatt afeefa-Logo, drinnen dann der Text auf die restlichen 3 A5-Seiten verteilt? Dann hat man nur eine A5-Seite Text auf einmal. Die Box für Link VII ist auch breiter als die anderen, soll das so?

**Comment by sjmielke** [comment]
> Die Box für Link VII ist auch breiter als die anderen, soll das so?

Ne, aber hatte micht nicht so gestört. Könnte man mit ein bisschen Boxspielereien sicher auch beheben.

**Comment by foobar0112** [comment]
Das Faltblatt finde ich gut, auch die Lösung mit den Fußnoten. Sieht schick aus.

Aber wenn es dann in der Mitte gefaltet ist und nur drin liegt, sieht es wirklich nicht mehr dazugehörig aus, wäre aber auch halb so wild, doch eine so riesige Afeefa Werbung bräuchte es dann vielleicht auch wieder nicht.

Was haltet ihr davon den, zugegeben etwas langen Text auf zwei A5 Seiten aufzuteilen, eine A5-Seite Afeefa-Werbung zu machen und die vierte Seite zum entzerren unseres Layouts zu verwenden? Dann hätte man wieder vier komplett und könnte es ins Heft reinnehmen.

Heft im Heft mit Afeefa vorn sieht dann vielleicht auch wieder komisch aus, so als ob das ein Afeefa-Heft wäre. Ist zwar eine Themengruppe, hat aber prinzipiell ja aber nichts miteinander zu tun...

**Comment by foobar0112** [comment]
So: habe das Faltblatt jetzt als zwei Seiten vorm Glossar integriert, die Links werden dadurch so viele, dass das Fakultätsbild nicht mehr unter die Auflistung passt, wie richtig von @sjmielke prophezeit. Dieses habe ich aber in die Modulübersicht geschoben und auch dort etwas umsortiert, genauso wie in der Checklist, da sind die Bilder nun etwas verteilt zugunsten der Umbrüche, schaut es euch einfach mal an. 

Insgesamt kommt da nun auch eine Seite mehr raus, plus Afeefa wären wir also bei 52 im ganzen. Das passt ja, allerdings passt die Reihenfolge mit außen/innen nicht mehr so, dass Themen nebeneinander liegen, da müsste man irgendetwas noch schlau vertauschen, Ideen?

**Comment by foobar0112** [comment]
Es wäre gelöst, wenn man den Auditoriumstext, der nur eine Seite fasst, hinter das Countdown, vor ZIH schiebt, dann passt alles wieder. \o/ Meinungen!?

**Comment by foobar0112** [comment]
ein Foto auf die zwei Seiten zu den Flüchtlingen wäre auch nicht schlecht, was könnte man da nehmen...? Ein Bild der USZ-Halle mit Feldbetten? Ein Bild der Zeltstadt? Fliehende Menschen an der ungarischen Gränze, weinende Kinder?

**Comment by foobar0112** [comment]
so, passt so, **NUR**, dass nach dem FSR, aus mir unerfindlichen Gründen eine leere Seite eingefügt wird, kannst du dir das bitte mal anschauen, @sjmielke?

**Comment by sjmielke** [comment]
Erstmal vorweg: ich finde es absolut **kacke**, dass wir jetzt eine Woche nach Redaktionsschluss plötzlich anfangen müssen, große neue Textblöcke zu schreiben (mal ganz abgesehen davon, dass ich zwei Textseiten ne ganz schöne Menge finde in einem Heft was möglichst wenig erschlagen soll), einzugliedern und an allen anderen Stellen rumzuschieben, auch wenn es nur Fotos, xkcds und ganze Artikel sind. Vor allem weil all das natürlich *längst* hätte passieren können.

Gut, das vorneweg, im Folgenden eine Liste, der Dinge die mir konkret nicht gefallen:
  * die Checklist war vorher (bis auf eine Zeile, die wir schon noch gefixt hätten) super auf einer Doppelseite untergebracht - das ist jetzt nicht mehr der Fall. Ich weiß nicht, ob jemand sich das Ding tatsächlich hergenommen hat und Haken gesetzt hat, aber dann wiederum weiß ich ja sowieso nicht, wer das Ding hier nutzt...
  * die Modulübersicht mit Bildern zu zertrennen gefällt mir irgendwie so garnicht - und viele Seiten, gerade natürlich die letzte sind mir persönlich auch irgendwie zu leer. Vielleicht sind die zwei Sachen aber auch nur Gewohnheit, weiß ich nicht.
  * die FSR-Gesichter sind zerteilt, aber da hast du ja schon nen sinnvollen Vorschlag gemacht, um das zu fixen
  * der Flüchtlingsartikel:
    - der eine Link ist kein Link, der müsste getrennt werden, hab ich übersehen - die anderen sollten soweit möglich https-ifiziert werden, da fliegt dann auch schonmal das USZ-Duplikat raus
    - ein Foto von Feldbetten wäre vielleicht ganz nett, das passt dann ja auch noch auf die zwei Seiten
  * die Afeefa-Werbung ist zum einen da irgendwie doof platziert (warum nicht direkt neben dem Flüchtlingsartikel? Hätte den positiven Nebeneffekt, dass der Campusplan auf der letzten Seite einfach aufschlagbar ist und dass alle Links auf einer Doppelseite stehen) und zum anderen... gibts die eigentlich überhaupt schon? Oder ist das auch noch mehr so Wunschdenken und wird irgendwann dann nachgereicht? Schlimm genug, dass wir auf die andere Werbung warten müssen, aber hier haben wir jemand engagierten, der sich da tatsächlich eigentlich gerade drum kümmert, aber nicht nur passiert nüscht, bis es in die finale Phase geht, sondern es gibt auch jetzt, eine Woche in den August, immernoch rein garnichts zum Vorzeigen? Wäre gut, wenn da mal bald ein ordentliches PDF auftauchen würde...

**Meinen rant-igen Tonfall bitte nur begrenzt ernst nehmen, ich hab heute noch nix ordentliches gegessen und hier ist schon fast Abend.**

**Comment by foobar0112** [comment]
Ich kann deinen Unmut ja verstehen, aber der Redaktionsschluss ist ja eingehalten, denn das heißt nur, dass keine Inhalte mehr kommen, was wir jetzt noch machen ist doch nur Layouting. 

Die große Umherschieberei war nur ein Versuch die durch Behebung der Schusterjungen und Hurenkinder neu hinzugekommenen Umbrüche, die Doppelseitigkeit nicht aushebeln zu lassen.

Die Checklist passte leider nicht auf zwei Seiten und das xkcd unter der Modulübersicht passte auch nicht mehr hin, allerdings eben in die Mitte (was ich jetzt nicht so schlimm finde). 

Die Afeefa-Werbung wird gerade gemacht und ist spätestens morgen da, die binde ich so schnell wie möglich ein. Ich finde es allerdings besser, wenn sie wie alle Werbungen hinten ist, aber es steht dir frei auch noch ein bisschen herumzuschieben.

**Comment by sjmielke** [comment]
> keine Inhalte mehr kommen

Ja, jetzt, nachdem dem du dir zwei Seiten Text etliche Tage nach besagtem Schluss aus dem Ärmel geschüttelt hast - und dabei ist der ja auch noch nicht mal so wirklich fest, du willst da ja vielleicht noch mit Bildern herumspielen etc.

> doch nur Layouting

Gut, das hat an sich nix mit Redaktionsschluss zu tun. Ein bisschen doof finde ich das trotzdem, das jetzt noch zu machen (und nur ein bisschen Layouting ist das Erdbeben, was da tobt, ja auch wirklich nicht).

> Die Checklist passte leider nicht auf zwei Seiten

Öh... doch? Bis auf eine Zeile, aber die hätten wir schon noch unterbekommen.

> Die Afeefa-Werbung wird gerade gemacht und ist spätestens morgen da

Bin gespannt - mal sehen, wer zuerst kommt, Binomi oder Afeefa :P

**Comment by sjmielke** [comment]
Apropos Redaktionelles:
Z. 7: "[citation needed]" - wenn dem so ist, wo ist die dann?
Z. 15: den kaputten Pseudolink bitte aufsplitten.
Generell vielleicht nochmal drüber nachdenken, ob die Links so sinnvoll und sinnvoll positioniert sind.
Wäre natürlich auch super, wenn jemand ( @dirkonet ?) nochmal drüberlesen könnte, ob da größere sprachliche Fehler drin sind.

**Comment by foobar0112** [comment]
@dirkonet, ja fände ich auch nett, oder hattest du im Pad schon drübergeschaut.

Links angepasst.

**Comment by dirkonet** [comment]
Hatte im Pad schon mal drübergeschaut, jetzt nicht noch mal. Das mit dem DNN-Foto geht so übrigens gar nicht und kann sehr teuer werden. Löscht das bitte endgültig aus diesem Repo, auch aus der History.

**Comment by sjmielke** [comment]
Hweeee, Geschichtsrevisionismus! Hab den commit jetzt raus-ge-rebase-t, die neue History force-ge-push-t und danach den branch protecte-t (tolles neues GitHub-Feature).
Alle, die weiter als @foobar0112s Commit 50f519bb6a0403860762c832f51d173cd4673be6 gepullt haben, bitte jetzt schreiend im Kreis herum rennen und alles löschen und neu klonen. Oder wenn sie wissen, was hier passiert ist und wie man damit umgeht git fetch machen und entsprechend rebasen.
Bitte nicht wieder alles reinmergen, so wie es eben noch passiert ist - ich hab ne Weile kein Internet mehr und Historys umschreiben wird immer blöder, je länger man damit wartet.
Sorry an alle, die bereits gepullt hatten.

**Comment by foobar0112** [comment]
:DDDDDDDDDDD

**Comment by foobar0112** [comment]
Also das Bild nehme ich jetzt wieder rein, ja? Ich habe mit den DNN, und der Fotografin Julia Vollmer gesprochen, wir dürfen es verwenden.

**Comment by dirkonet** [comment]
Mir wäre wohler, wenn wir das schriftlich hätten.

**Comment by foobar0112** [comment]
Sie hat mir eine Mail geschrieben (die irgendwo im Spamfilter, wegen zu großem Anhang, oder ihrer Unfähigkeit - kA hängen geblieben ist) Was besseres bekommen wir in der kürze der Zeit nicht, sie hat es mir telefonisch zugesichert - ich habe da keine Bedenken. So, wie es jetzt gekennzeichnet ist, reicht es, nach ihreren Angaben und die Urheberin hat zusätzlich das OK gegeben. Nicht zufrieden, Dirk?

**Comment by dirkonet** [comment]
Danke für's Organisieren der Bildrechte :) Kannst die Mail ja noch irgendwie auf die kaki in den ESE-NoPanic-Ordner "archivieren".

**Comment by foobar0112** [comment]
ja nunja, wenn sie denn noch eintrudelt, bisher habe ich die mail noch nicht zu gesicht bekommen...

**Comment by sjmielke** [comment]
Ansonsten nochmal eine Mail an eine andere Adresse erbeten oder so? Wenn das erledigt ist, kannst du das Issue hier ja auch schließen.

**Comment by dirkonet** [comment]
Ich hab mal noch Lars' Anmerkungen bzgl. USZ vs. Sportstätten eingepflegt.

**Comment by foobar0112** [comment]
danke. ja, ich hoffe da kommt noch was von der dame
