### ISSUE TITLE
FSR-Logo Spieleabendplakat

### ISSUE THREAD

**Issue by kalinni** [fsr/nopanic#95]
Da ist noch das Plakat mit dem alten Logo drin...

**Comment by foobar0112** [comment]
:scream:

**Comment by jgonsior** [comment]
Wo zur Hölle findet man denn eine aktuelle Version des Plakats?!

**Comment by sjmielke** [comment]
Das hat soweit ich weiss, jedes Mal Simon auch bloss so zusammengehackt - glaube nicht, dass es da was ordentliches gibt. Also selber machen oder warten, dass ich es am Montag mache oder so? :D

**Comment by jgonsior** [comment]
Na dann überlasse ich das doch großzügigerweise dir.

**Comment by sjmielke** [comment]
2d6da08cded3bd9c0025e4c239d3f3a4939191df
