### ISSUE TITLE
Schriftzug "no panic" pixlig

### ISSUE THREAD

**Issue by dirkonet** [fsr/nopanic#97]
Der Schriftzug auf dem Cover ist pixlig – jedoch nur der Text, die Zahl ist vektoriös. Bitte prüfen, was da schief gegangen ist, damit das nächstes Jahr nicht noch einmal passiert – alternativ Auflösung weiter verringern, dann sieht es wieder nach Absicht aus.

**Comment by sjmielke** [comment]
Jop, hatten wir ja schon gesehen - das hat Inkscape tatsächlich so exportiert, da scheint also der PDF-Exporter falsch konfiguriert gewesen zu sein. Eigentlich ist das aber alles über ein paar Formathürden nur aus 2014 übernommen und da wars ja nicht so oder? Muss man halt nächstes Mal drauf achten.

**Comment by dirkonet** [comment]
Der Bug besteht noch.

**Comment by sjmielke** [comment]
Ist ja auch nicht geschlossen :P Aber danke für den Hinweis.
