### ISSUE TITLE
Strategiespielpratikum

### ISSUE THREAD

**Issue by sjmielke** [fsr/nopanic#99]
Robolab ist drin, aber das zweite Praktikum für die Diplomer fehlt in der Modulübersicht.

**Comment by jgonsior** [comment]
Es steht drinnen: "Für Diplomstudenten gibt es zusätzlich ein einwöchiges Einzelprojekt, bei dem man zeigen kann, was man in C oder wahlweise C++ drauf hat. Alternativ kann das Strategiespielepraktikum auch auf das Sommersemester verschoben werden.
In den letzten Jahren war eine KI für bekannte Brettspiele gefragt." Reicht dir das nicht aus?

**Comment by sjmielke** [comment]
Oh. Das hat wer auch immer sich bei mir beschwert hatte dann wohl überlesen (und ich habs nicht genau nachgeschaut) :smile: 
Und ich sehe gerade dass das ja im Diplom auch wirklich nur ein Modul zu sein scheint. Dann isses so ja an sich genau richtig.
